ALTER TABLE members ADD COLUMN email TEXT;
ALTER TABLE members ADD COLUMN password_hash TEXT;
ALTER TABLE members ADD COLUMN salt TEXT;
ALTER TABLE members ADD COLUMN role TEXT NOT NULL DEFAULT 'member';
ALTER TABLE members ADD COLUMN active INTEGER NOT NULL DEFAULT 1;
CREATE UNIQUE INDEX members_email ON members(email);
ALTER TABLE opportunities ADD COLUMN version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE opportunities ADD COLUMN notes TEXT NOT NULL DEFAULT '';
ALTER TABLE opportunities ADD COLUMN quote TEXT NOT NULL DEFAULT '{}';
ALTER TABLE opportunities ADD COLUMN last_mutation TEXT;
ALTER TABLE tasks ADD COLUMN kind TEXT NOT NULL DEFAULT 'task';
CREATE TABLE invitations (token_hash TEXT PRIMARY KEY, role TEXT NOT NULL DEFAULT 'member', created_by TEXT, expires_at TEXT NOT NULL, consumed_at TEXT);
CREATE TABLE invite_claims (token_hash TEXT PRIMARY KEY, member_id TEXT NOT NULL);
CREATE TABLE catalog (id TEXT PRIMARY KEY, kind TEXT NOT NULL DEFAULT 'opportunity', payload TEXT NOT NULL, deadline TEXT, checked_at TEXT NOT NULL, source TEXT NOT NULL DEFAULT 'PNCP');
CREATE INDEX catalog_deadline ON catalog(kind, deadline);
CREATE TABLE settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE document_text (url TEXT PRIMARY KEY, text TEXT NOT NULL, extracted_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ai_studies (id TEXT PRIMARY KEY, opportunity_id TEXT NOT NULL REFERENCES opportunities(opportunity_id), member_id TEXT NOT NULL REFERENCES members(id), question TEXT NOT NULL, answer TEXT NOT NULL, document_name TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX ai_studies_opportunity ON ai_studies(opportunity_id, created_at DESC);
CREATE TABLE request_limits (bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, expires_at INTEGER NOT NULL);
