import {chromium} from '../tr-assistant/node_modules/playwright/index.mjs';
import {stubAutomaticReview} from './helpers.mjs';
import assert from 'node:assert/strict';
const base=process.env.TEST_BASE||'http://localhost:8787',browser=await chromium.launch({headless:true,channel:'chromium'}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const newTitle='QA UX: pedir cotação '+crypto.randomUUID().slice(0,8),editedTitle=newTitle+' revisada';
const id='78316064000193-1-000033/2026',path='/opportunities/'+encodeURIComponent(id);
async function api(route,method='GET',body){return page.evaluate(async({route,method,body})=>{const r=await fetch('/api'+route,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};},{route,method,body});}
async function tab(name){await page.locator('.tabs [data-detail-tab='+name+']').click();}
async function savePrice(){await Promise.all([page.waitForResponse(r=>r.request().method()==='PATCH'&&r.url().includes('/opportunities/')),page.locator('[data-action=save-quote]').click()]);}
try{
  await stubAutomaticReview(page,base);
  await page.goto(base+'/');await page.locator('[data-swipe-card]').waitFor();await page.locator('nav [data-view=board]').click();await page.locator('.card').first().waitFor();
  await page.locator('#search').fill('46634598000171-1-000452/2026');assert.equal(await page.locator('.card').count(),0,'The cleaning-product false positive must not be an AD PRO opportunity');
  await page.locator('#clear-filters').click();await page.getByText('Entrar na equipe',{exact:true}).click();await page.locator('[name=email]').fill('qa.alice@licitacoes.test');await page.locator('[name=password]').fill('Local-QA-9Oct!2026');await page.locator('#auth-form button').first().click();await page.locator('.account').waitFor();
  const initialDetail=(await api(path+'/detail')).body,initial=initialDetail.work,mode=initialDetail.review?.bidRule?.mode,qaIds=(await api('/workspace')).body.members.filter(m=>['qa.alice@licitacoes.test','qa.bob@licitacoes.test'].includes(m.email)).map(m=>m.id);assert.ok(!initial.updated_by||qaIds.includes(initial.updated_by),'QA must not overwrite work from a real team member');if(mode==='lot'||mode==='item'){const response=await api(path+'/bids','POST',{id:crypto.randomUUID(),version:initial.version,amount:1000,basis:'total',acknowledgeUnknownCost:true});assert.equal(response.status,400);assert.match(response.body.error,mode==='lot'?/lotes\/grupos/:/por item/);console.log(JSON.stringify({result:'PASS',base,mode,checks:['official judgment rule guards incompatible contract-wide bids','no unsupported bid prepared']}));}else{await api(path,'PATCH',{stage:'cotacao',ownerId:initial.owner_id,version:initial.version,goal:initial.goal,notes:initial.notes,quote:{...JSON.parse(initial.quote),unitFloors:{},selectedItems:{},minimumTotal:undefined}});await page.locator('#refresh-workspace').click();
  await page.locator('#search').fill(id);await page.locator('[data-quick-bid]').first().click();await page.locator('#bid-form').waitFor();assert.ok(await page.getByText('Preparar lance',{exact:true}).isVisible());
  await tab('quote');await page.locator('#quote-extra summary').click();await page.locator('[data-quote=licenses]').fill('790');for(const key of ['hours','hourly','infra','support','other','contingency'])await page.locator('[data-quote='+key+']').fill('0');await page.locator('[data-quote=tax]').fill('6');await page.locator('[data-quote=margin]').fill('15');if(await page.locator('#use-item-costs').count())await page.locator('#use-item-costs').uncheck();
  await tab('docs');await tab('quote');assert.equal(await page.locator('[data-quote=licenses]').inputValue(),'790','Price draft must survive tab changes');await savePrice();await tab('bids');
  await page.locator('#bid-amount').fill('999,99');assert.ok(await page.locator('#bid-form button[type=submit]').isDisabled());assert.match(await page.locator('#bid-feedback').textContent(),/Abaixo/);
  const detail=(await api(path+'/detail')).body;
  const rejected=await api(path+'/bids','POST',{id:crypto.randomUUID(),version:detail.work.version,amount:999.99,basis:'total'});assert.equal(rejected.status,400,'Backend must enforce the floor even when the UI is bypassed');
  await page.locator('#bid-amount').fill('1.000,00');await page.locator('#bid-portal').fill('https://www.comprasnet.gov.br/seguro/loginPortal.asp');
  const responsePromise=page.waitForResponse(r=>r.url().endsWith('/bids')&&r.request().method()==='POST');await page.locator('#bid-form button[type=submit]').click();const response=await responsePromise;assert.equal(response.status(),201);const prepared=(await response.json()).bid;
  await page.locator('[data-copy-bid="'+prepared.id+'"]').waitFor();const afterPrepare=(await api(path+'/detail')).body;assert.equal(afterPrepare.bids.find(b=>b.id===prepared.id).status,'prepared');assert.notEqual(afterPrepare.work.stage,'disputada','Preparing must never falsely mark a bid as submitted');
  const repeated=await api(path+'/bids','POST',JSON.parse(response.request().postData()));assert.equal(repeated.status,201);assert.equal(repeated.body.idempotent,true);
  await page.locator('[data-report-bid="'+prepared.id+'"]').click();await page.locator('#report-form').waitFor();assert.ok(await page.locator('#report-form').evaluate(form=>!form.checkValidity()),'Manual confirmation is required');await page.locator('#report-confirm').check();await page.locator('#report-receipt').fill('QA UX: registro de teste, nenhum lance real enviado');
  const reportPromise=page.waitForResponse(r=>r.url().endsWith('/report'));await page.locator('#report-form button[type=submit]').click();assert.equal((await reportPromise).status(),200);await page.waitForFunction(()=>!document.querySelector('#report-dialog').open);
  const reported=(await api(path+'/detail')).body;assert.equal(reported.bids.find(b=>b.id===prepared.id).status,'reported');assert.equal(reported.work.stage,'disputada');assert.ok(reported.activity.some(a=>a.action==='Envio informado manualmente'));
  await tab('tasks');await page.locator('#task-extra summary').click();await page.locator('#task-form [name=title]').fill(newTitle);await page.locator('#task-form button[type=submit]').click();await page.getByText(newTitle,{exact:true}).waitFor();
  const task=(await api(path+'/detail')).body.tasks.find(t=>t.title===newTitle);await page.locator('[data-edit-task="'+task.id+'"]').click();await page.locator('#task-form [name=title]').fill(editedTitle);await page.locator('#task-form [name=dueAt]').fill('2026-10-16');await page.locator('#task-form button[type=submit]').click();await page.getByText(editedTitle,{exact:true}).waitFor();
  page.once('dialog',d=>d.accept());await page.locator('[data-archive-task="'+task.id+'"]').click();await page.waitForFunction(title=>![...document.querySelectorAll('.task-title')].some(e=>e.textContent===title),editedTitle);assert.ok(!(await api(path+'/detail')).body.tasks.some(t=>t.id===task.id));
  await tab('bids');await page.screenshot({path:'/tmp/licitacoes-lances-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});assert.ok(await page.locator('.portal-fact').isVisible());assert.ok(await page.locator('#bid-form button[type=submit]').isVisible());await page.screenshot({path:'/tmp/licitacoes-lances-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',base,bid:prepared.id,checks:['AD PRO default excludes the reported cleaning product','visible bid action','preserved price draft','client and server floor validation','prepared does not mean submitted','retry is idempotent','explicit manual submission record','editable and archivable tasks','mobile portal access','no JavaScript errors']}));
}
}catch(error){console.error(JSON.stringify({toast:await page.locator('#toast').textContent(),taskForm:await page.locator('#task-form').count()?await page.locator('#task-form').evaluate(form=>({id:form.id,title:form.elements.title.value,hidden:form.closest('details').open})):null}));await page.screenshot({path:'/tmp/licitacoes-bid-failure.png',fullPage:true});throw error;}finally{await browser.close();}
