import {chromium} from '../tr-assistant/node_modules/playwright/index.mjs';
import AxeBuilder from '../tr-assistant/node_modules/@axe-core/playwright/dist/index.mjs';
import {stubAutomaticReview} from './helpers.mjs';
import assert from 'node:assert/strict';
const base=process.env.TEST_BASE||'http://localhost:8787',realAI=process.env.TEST_REAL_AI==='1',browser=await chromium.launch({channel:'chromium',headless:true}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));const chosenMaterial=realAI?'0':'-1';const id='78316064000193-1-000033/2026',path='/opportunities/'+encodeURIComponent(id),checks=[];
async function api(route,method='GET',body){return page.evaluate(async({route,method,body})=>{const r=await fetch('/api'+route,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};},{route,method,body});}
async function axe(name){const result=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(result.violations.map(v=>({id:v.id,examples:v.nodes.slice(0,2).map(n=>n.html)})),[],name+' accessibility');checks.push(name+' automated accessibility');}
try{
  await stubAutomaticReview(page,base);
  await page.goto(base);await page.locator('[data-swipe-card]').waitFor();await page.getByText('Entrar na equipe',{exact:true}).click();await page.locator('[name=email]').fill('qa.alice@licitacoes.test');await page.locator('[name=password]').fill('Local-QA-9Oct!2026');await page.locator('#auth-form button').first().click();await page.locator('.account').waitFor();
  const member=(await api('/me')).body.member,d=(await api(path+'/detail')).body;assert.ok(!d.work.updated_by||d.work.updated_by===member.id,'Do not overwrite work from a real team member');
  const reset=await api(path,'PATCH',{stage:'nova',version:d.work.version,ownerId:d.work.owner_id,goal:d.work.goal,notes:d.work.notes,quote:JSON.parse(d.work.quote)});assert.equal(reset.status,200);await page.locator('#search').fill(id);await page.locator('#refresh-workspace').click();await page.waitForFunction(({id,version})=>document.querySelector('[data-swipe-card="'+id+'"]')?.dataset.version===String(version),{id,version:reset.body.version});
  await page.locator('[data-inline-floor]').first().waitFor();assert.ok(await page.locator('[data-inline-floor]').first().isVisible(),'Minimum is visible on the initial summary');assert.equal(await page.locator('[data-inline-tab=overview]').getAttribute('aria-selected'),'true');const field=page.locator('[data-inline-floor]').first(),key=await field.getAttribute('data-inline-floor');await field.fill('147,1234');
  await page.locator('[data-inline-tab=ai]').first().click();await page.locator('[data-inline-ai-field=question]').fill('QA inline: qual é o prazo da licença e o período de suporte?');await page.locator('[data-inline-ai-field=documentIndex]').selectOption(chosenMaterial);await page.locator('[data-inline-tab=products]').first().click();assert.equal(await field.inputValue(),'147,1234','Draft survives inline tab changes');
  const saved=page.waitForResponse(r=>r.request().method()==='PATCH'&&r.url().endsWith(encodeURIComponent(id)));await page.locator('[data-inline-save-floors]').click();assert.equal((await saved).status(),200);await page.waitForFunction(()=>document.querySelector('#toast').textContent==='Mínimos e produtos selecionados salvos para a equipe');
  const stored=(await api(path+'/detail')).body,q=JSON.parse(stored.work.quote);assert.equal(q.unitFloors[key],147.1234);assert.equal(await page.locator('#detail').evaluate(d=>d.open),false);await axe('inline product floors');await page.screenshot({path:'/tmp/licitacoes-inline-produtos-desktop.png',fullPage:true});
  await page.locator('[data-inline-tab=docs]').first().click();await page.locator('.inline-pdf').waitFor();assert.match(await page.locator('.inline-pdf').getAttribute('src'),/inline=1/);const preview=await page.evaluate(async path=>{const r=await fetch('/api'+path+'/download?index=0&inline=1');return {status:r.status,type:r.headers.get('content-type'),disposition:r.headers.get('content-disposition'),head:new TextDecoder().decode((await r.arrayBuffer()).slice(0,4))};},path);assert.equal(preview.status,200);assert.match(preview.type,/application\/pdf/);assert.match(preview.disposition,/inline/);assert.equal(preview.head,'%PDF');await axe('inline official PDF');
  await page.locator('[data-inline-tab=ai]').first().click();assert.ok(await field.isVisible(),'Minimum remains visible next to AI');assert.match(await page.locator('[data-inline-ai-field=question]').inputValue(),/^QA inline:/);assert.equal(await page.locator('[data-inline-ai-field=documentIndex]').inputValue(),chosenMaterial);
  if(!realAI)await page.route('**/api'+path+'/study',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({id:'ui-test-only',answer:'Resposta simulada exclusivamente no teste de interface; não é resultado real de IA.',documentName:'Objeto e produtos do cadastro'})}));
  const answerPromise=page.waitForResponse(r=>r.url().endsWith('/study'),{timeout:180000});await page.locator('[data-inline-ai=ask]').click();await page.locator('[data-inline-tab=products]').first().click();const response=await answerPromise;assert.equal(response.status(),200,JSON.stringify(await response.json()));const answer=await response.json();await page.locator('[data-inline-tab=ai]').first().click();await page.locator('.inline-answer').waitFor();assert.match(await page.locator('.inline-answer').textContent(),new RegExp(answer.answer.slice(0,10).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));if(realAI)assert.ok((await api(path+'/detail')).body.studies.some(s=>s.id===answer.id));await axe('inline AI questions');
  await page.locator('[data-inline-tab=overview]').first().click();assert.ok(await page.locator('.tender-brief').isVisible());await page.locator('[data-inline-tab=ai]').first().click();assert.match(await page.locator('[data-inline-ai-field=question]').inputValue(),/^QA inline:/);assert.equal(await page.locator('[data-inline-ai-field=documentIndex]').inputValue(),chosenMaterial);
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:'/tmp/licitacoes-inline-ia-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const actions=await page.locator('.swipe-actions').boundingBox();assert.ok(actions.y+actions.height<=844);assert.equal(await page.locator('#detail').evaluate(d=>d.open),false);assert.deepEqual(errors,[]);
  console.log(JSON.stringify({result:'PASS',base,realAI,checks:[...checks,'minimum always visible on initial screen and beside tabs','edital/TR critical brief from selected source','manual unit floor persisted with four decimal places','drafts preserved between inline tabs','real PDF served inline with correct headers','question and chosen source preserved','AI response stays accessible after tab change','no detail dialog or page navigation','mobile actions remain visible','no JavaScript errors']}));
}catch(error){await page.screenshot({path:'/tmp/licitacoes-inline-failure.png',fullPage:true});throw error;}finally{await browser.close();}
