import {chromium} from '../tr-assistant/node_modules/playwright/index.mjs';
import AxeBuilder from '../tr-assistant/node_modules/@axe-core/playwright/dist/index.mjs';
import assert from 'node:assert/strict';
const base=process.env.TEST_BASE||'http://localhost:8787',real=process.env.TEST_REAL_AI==='1',browser=await chromium.launch({channel:'chromium',headless:true}),context=await browser.newContext({viewport:{width:1600,height:1000}}),page=await context.newPage(),errors=[],id='78316064000193-1-000033/2026';
page.on('pageerror',error=>errors.push(error.message));let mode='item',catalog=[];
async function api(path,method='GET',body){return page.evaluate(async({path,method,body})=>{const r=await fetch('/api'+path,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};},{path,method,body});}
const route='/opportunities/'+encodeURIComponent(id);
try{
  if(!real)await page.route('**/api/opportunities/*/review',async request=>{const key=decodeURIComponent(new URL(request.request().url()).pathname.split('/').at(-2)),r=catalog.find(r=>r.id===key);assert.ok(r);await request.fulfill({status:200,contentType:'application/json',body:JSON.stringify({opportunity:r,review:{status:'ready',bidRule:{mode,quote:mode==='item'?'SIMULAÇÃO: menor preço por item.':'SIMULAÇÃO: menor preço global.',source:'Arquivo simulado no teste de interface'},documents:[{name:'SIMULAÇÃO DE TESTE · não é extração real',index:0,points:[{label:'Vigência',detail:'Prazo simulado exclusivamente neste teste.',reference:'Seção simulada'}]}]}})});});
  await page.goto(base);await page.locator('[data-swipe-card]').waitFor();catalog=(await api('/catalog')).body.catalog;
  assert.equal(await page.locator('[data-goal-choice]').count(),0);assert.ok(await page.locator('.onepage-category').isVisible());assert.ok(await page.locator('.tender-identity').isVisible());const box=await page.locator('.swipe-card').boundingBox();assert.ok(box.y<250,'Card moves up on the first screen');
  await page.getByText('Entrar na equipe',{exact:true}).click();await page.locator('[name=email]').fill('qa.alice@licitacoes.test');await page.locator('[name=password]').fill('Local-QA-9Oct!2026');await page.locator('#auth-form button').first().click();await page.locator('.account').waitFor();
  const initial=(await api(route+'/detail')).body.work,qaIds=(await api('/workspace')).body.members.filter(m=>m.email==='qa.alice@licitacoes.test'||m.email==='qa.bob@licitacoes.test').map(m=>m.id);assert.ok(!initial.updated_by||qaIds.includes(initial.updated_by),'Never overwrite real team work');
  const reset=await api(route,'PATCH',{stage:'nova',version:initial.version,ownerId:initial.owner_id,notes:initial.notes,quote:real?JSON.parse(initial.quote):{},goal:initial.goal,declineReason:''});assert.equal(reset.status,200);await page.locator('#search').fill(id);await page.locator('#refresh-workspace').click();
  if(real){await page.waitForFunction(()=>document.querySelectorAll('.document-point').length>0||document.querySelector('.tender-brief .warning'),{},{timeout:180000});const data=(await api(route+'/detail')).body;assert.ok(data.review);assert.equal(data.review.status,'ready',JSON.stringify(data.review));assert.ok(data.review.documents.length>0);assert.ok(await page.locator('.document-point').first().isVisible());const mode=data.review.bidRule?.mode;if(mode==='lot'||mode==='package'||mode==='unknown')assert.equal(await page.locator('[data-inline-include]:enabled').count(),0,'No unverified product exclusion');if(mode!=='item'){const incompatible=await api(route+'/bids','POST',{id:crypto.randomUUID(),version:data.work.version,amount:1000,basis:'unit',itemIndex:0,acknowledgeUnknownCost:true});assert.equal(incompatible.status,400);assert.match(incompatible.body.error,/edital|lotes\/grupos/);}}
  else{await page.locator('.document-point').first().waitFor();assert.ok(await page.locator('[data-inline-include]').first().isEnabled());const fields=page.locator('.product-line [data-inline-floor]');for(let i=0;i<await fields.count();i++){const item=catalog.find(r=>r.id===id).it[i],price=Math.floor(Number(item.vu||1)*5000)/10000;await fields.nth(i).fill(price.toFixed(4).replace('.',','));}const totalBefore=await page.locator('[data-inline-total]').textContent();await page.locator('[data-inline-include]').first().uncheck();assert.notEqual(await page.locator('[data-inline-total]').textContent(),totalBefore);assert.equal(await fields.first().isDisabled(),true);assert.ok(await page.locator('.product-line.excluded').count());const unsupported=await api(route,'PATCH',{stage:'nova',version:(await api(route+'/detail')).body.work.version,quote:{selectedItems:{1:false}}});assert.equal(unsupported.status,400,'UI simulation cannot bypass server proof of item bidding');await page.locator('[data-inline-include]').first().check();const save=page.waitForResponse(r=>r.request().method()==='PATCH'&&r.url().endsWith(encodeURIComponent(id)));await page.locator('[data-inline-save-floors]').click();assert.equal((await save).status(),200);await page.waitForLoadState('networkidle');mode='package';await page.reload();await page.locator('.account').waitFor();await page.locator('#search').fill(id);await page.getByText('O edital exige pacote completo.',{exact:false}).first().waitFor();assert.equal(await page.locator('[data-inline-include]:enabled').count(),0);}
  for(const width of [320,390,768,1600]){await page.setViewportSize({width,height:1000});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No horizontal page overflow at '+width);}
  const axe=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();assert.deepEqual(axe.violations.map(v=>({id:v.id,nodes:v.nodes.slice(0,2).map(n=>n.html)})),[]);await page.screenshot({path:'/tmp/licitacoes-onepage-desktop.png',fullPage:true});assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',base,realAI:real,checks:real?['card near top','category without form','identification and city','real automatic PDF points without clicking','real rule blocks incompatible product bid and exclusion','four viewport widths','automated accessibility','no JavaScript errors']:['card near top','category instead of objective form','tender identification and city','product rows and live subtotal/total','automatic edital/TR points without clicking','conditional item exclusion with server validation','package indication and no item exclusion','single page at four widths','automated accessibility','no JavaScript errors']}));
}catch(error){await page.screenshot({path:'/tmp/licitacoes-onepage-failure.png',fullPage:true});throw error;}finally{await browser.close();}
