import {chromium} from '../tr-assistant/node_modules/playwright/index.mjs';
import {stubAutomaticReview} from './helpers.mjs';
import {inferGoal} from '../app/goals.js';
import assert from 'node:assert/strict';
const base=process.env.TEST_BASE||'http://localhost:8787',browser=await chromium.launch({headless:true,channel:'chromium'}),context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
page.on('pageerror',e=>errors.push(e.message));
const id='78316064000193-1-000033/2026',path='/opportunities/'+encodeURIComponent(id);
async function api(route,method='GET',body){return page.evaluate(async({route,method,body})=>{const r=await fetch('/api'+route,{method,headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});return {status:r.status,body:await r.json()};},{route,method,body});}
async function detail(){const response=await api(path+'/detail');assert.equal(response.status,200,JSON.stringify(response.body));return response.body;}
async function reset(){const d=await detail();const result=await api(path,'PATCH',{stage:'nova',version:d.work.version,ownerId:d.work.owner_id,goal:'',declineReason:'',notes:d.work.notes,quote:JSON.parse(d.work.quote)});await page.locator('#refresh-workspace').click();await page.waitForFunction(({id,version})=>document.querySelector('[data-swipe-card="'+id+'"]')?.dataset.version===String(version),{id,version:result.body.version});}
async function decideByClick(selector){const pending=page.waitForResponse(r=>r.url().endsWith(encodeURIComponent(id))&&r.request().method()==='PATCH');await page.locator(selector).click();assert.equal((await pending).status(),200);}
async function undo(){await decideByClick('[data-undo-decision]');await page.locator('[data-swipe-card="'+id+'"]').waitFor();await page.waitForLoadState('networkidle');}
try{
  await stubAutomaticReview(page,base);
  await page.goto(base+'/');await page.locator('[data-swipe-card]').waitFor();assert.equal(await page.locator('[data-swipe-card]').count(),1);
  await page.getByText('Entrar na equipe',{exact:true}).click();await page.locator('[name=email]').fill('qa.alice@licitacoes.test');await page.locator('[name=password]').fill('Local-QA-9Oct!2026');await page.locator('#auth-form button').first().click();await page.locator('.account').waitFor();
  const member=(await api('/me')).body.member,initial=(await detail()).work;
  assert.ok(!initial.updated_by||initial.updated_by===member.id,'QA must not overwrite work last changed by a real team member');
  await page.locator('#search').fill(id);await reset();
  assert.equal(await page.locator('textarea:visible').count(),0,'Triage needs no text entry');assert.equal(await page.locator('[data-goal-choice]').count(),0);const expectedGoal=inferGoal((await detail()).opportunity);const floor=page.locator('[data-inline-floor]').first(),floorKey=await floor.getAttribute('data-inline-floor');assert.ok(await floor.isVisible(),'Minimum bid is on the first screen');await floor.fill('-1');assert.ok(await page.locator('[data-triage-accept]').isDisabled());assert.equal((await detail()).work.stage,'nova','Invalid pending floor blocks accepting');await floor.fill('189,4321');await decideByClick('[data-triage-accept]');await page.waitForFunction(()=>document.querySelector('nav [data-view=board]').classList.contains('active'));
  let d=await detail();assert.equal(d.work.stage,'compativel');assert.equal(d.work.goal,expectedGoal);assert.equal(JSON.parse(d.work.quote).unitFloors[floorKey],189.4321,'Accept saves floors and decision atomically');assert.equal(d.work.owner_id,initial.owner_id||member.id,'Preserve an existing owner; only auto-assign unowned work');assert.equal(await page.locator('[data-swipe-card]').count(),0,'Decided card leaves the new queue');
  await page.locator('[data-undo-decision]').waitFor();await undo();assert.equal((await detail()).work.stage,'nova');
  await page.locator('[data-triage-decline]').click();await page.locator('#decline-dialog').waitFor();assert.equal((await detail()).work.stage,'nova','Opening the reason picker must not save a decline');assert.equal(await page.locator('#decline-dialog textarea').count(),0);
  const withoutReason=await api(path,'PATCH',{stage:'declinada',version:(await detail()).work.version,goal:'ia'});assert.equal(withoutReason.status,400,'Server requires a structured reason');
  await page.locator('#decline-goal').selectOption('licencas');await decideByClick('[data-decline-reason=margem]');await page.waitForFunction(()=>!document.querySelector('#decline-dialog').open);d=await detail();assert.equal(d.work.stage,'declinada');assert.equal(d.work.decline_reason,'margem');assert.equal(d.work.goal,'licencas');assert.ok(d.activity.some(a=>a.detail?.includes('Margem ou preço inviável')));
  await page.locator('nav [data-view=declined]').click();await page.locator('.declined-card').filter({hasText:'Margem ou preço inviável'}).waitFor();await decideByClick('[data-reevaluate="'+id+'"]');await page.locator('[data-swipe-card]').waitFor();assert.equal((await detail()).work.decline_reason,'');
  await page.locator('.extra-filters summary').click();await page.locator('#filter-goal').selectOption('ia');assert.equal(await page.locator('[data-swipe-card]').count(),0,'Objective filter works');await page.locator('#filter-goal').selectOption('licencas');await page.locator('[data-swipe-card]').waitFor();await page.locator('.extra-filters summary').click();
  await page.locator('[data-swipe-card]').focus();const keyboard=page.waitForResponse(r=>r.request().method()==='PATCH'&&r.url().endsWith(encodeURIComponent(id)));await page.keyboard.press('ArrowRight');assert.equal((await keyboard).status(),200);await page.locator('[data-undo-decision]').waitFor();await undo();
  await page.setViewportSize({width:390,height:844});await page.locator('.swipe-card h2').evaluate(el=>el.scrollIntoView({block:'center'}));const box=await page.locator('.swipe-card h2').boundingBox(),session=await context.newCDPSession(page);
  await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:box.x+20,y:box.y+30}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:box.x+145,y:box.y+30}]});
  const swipe=page.waitForResponse(r=>r.request().method()==='PATCH'&&r.url().endsWith(encodeURIComponent(id)));await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal((await swipe).status(),200);await page.locator('[data-undo-decision]').waitFor();assert.equal((await detail()).work.stage,'compativel');await undo();
  await page.locator('.swipe-card h2').evaluate(el=>el.scrollIntoView({block:'center'}));const left=await page.locator('.swipe-card h2').boundingBox();await session.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:left.x+180,y:left.y+30}]});await session.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:left.x+50,y:left.y+30}]});await session.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await page.locator('#decline-dialog').waitFor();await decideByClick('[data-decline-reason=prazo]');assert.equal((await detail()).work.decline_reason,'prazo');await undo();
  assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No page-level overflow');assert.deepEqual(errors,[]);console.log(JSON.stringify({result:'PASS',base,checks:['one-card initial triage','no typing needed','structured objective','minimum on the first screen','accept saves floors and opens Kanban','accept shared with owner','mandatory decline reason on server','decline reason in history','declines dashboard','re-evaluate without deleting history','filter by objective','undo with version','keyboard decisions','real mobile touch swipes both directions','no JavaScript errors']}));
}finally{await browser.close();}
