import {stages,escape as e,normalize,dateTime,isLive,eligibleForBoard,minimumBid,calculateQuote} from './core.js';
import {classifyOpportunity} from './scope.js';
import {bidPane,bidRow,updateBidPreview,portalsPane,money as bidMoney} from './bidding.js';
import {parseAmount,decimalAmount,portalLink,bidMinimum} from './bid-math.js';
import {floorLimitError} from './bid-limits.js';
import {goals,declineReasons,goalLabel,reasonLabel,inferGoal} from './goals.js';
import {productsPane,filesPane,aiPane,floorPane,briefPane,updateInlineTotals} from './inline-opportunity.js';
import {triagePane,declinedPane} from './triage.js';
const $=s=>document.querySelector(s),brl=v=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fmt=s=>dateTime(s)?.toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})||'Sem data';
const initials=name=>String(name||'?').split(/\s+/).slice(0,2).map(w=>w[0]).join('').toUpperCase();
const S={member:null,members:[],catalog:[],tasks:[],bids:[],drafts:{},editingTask:null,pendingOpen:null,detailRequest:0,inlineTabs:{},inlineData:{},inlineDocument:{},inlineBusy:{},inlineLoading:{},autoReview:{},autoBusy:{},boardFocus:null,triageGoals:{},lastDecision:null,declineId:null,decisionBusy:false,view:'triage',detail:null,tab:'overview',sync:null,lastFullSync:null,filter:{q:'',uf:'',owner:'',service:'',deadline:'',scope:'adpro',goal:''},columnLimit:{},archive:[],loading:false};
let invite=new URLSearchParams(location.hash.slice(1)).get('invite');
let toastTimer,dragId,polling=false;
async function api(path,method='GET',body){
  let res;try{res=await fetch('/api'+path,{method,credentials:'same-origin',headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});}catch{throw new Error('Sem conexão. Seus rascunhos continuam nesta aba; tente novamente.');}
  const data=await res.json().catch(()=>({}));if(!res.ok){const error=new Error(data.error||'Falha na conexão.');error.status=res.status;throw error;}return data;
}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast'+(error?' error':'');el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,error?7500:3500);}
function needLogin(){if(S.member)return true;openAuth();return false;}
const stageName=s=>stages.find(([key])=>key===s)?.[1]||'Novas';
const memberName=id=>S.members.find(m=>m.id===id)?.name||'Sem responsável';
const ownerOptions=(selected='',empty='Sem responsável')=>'<option value="">'+empty+'</option>'+S.members.map(m=>`<option value="${e(m.id)}" ${m.id===selected?'selected':''}>${e(m.name)}</option>`).join('');
const stageOptions=selected=>stages.map(([key,label])=>`<option value="${key}" ${key===selected?'selected':''}>${label}</option>`).join('');
function deadline(r){const end=dateTime(r.fim);if(!end)return {label:'Sem prazo informado',class:''};const h=(end-Date.now())/3600000;if(h<=0)return {label:'Prazo encerrado',class:'urgent'};return {label:h<24?'Fecha em '+Math.max(1,Math.ceil(h))+'h':'Fecha em '+Math.ceil(h/24)+' dias',class:h<48?'urgent':h<168?'soon':''};}
function sourceInfo(){
  const sync=S.sync,el=$('#source-info');el.className='source-info'+(sync?.error?' error':'');
  if(sync?.error)el.textContent='Última coleta encontrou uma falha: '+sync.error+' · Retomada automática na próxima execução.';
  else if(sync?.cycleStarted)el.textContent=`● PNCP em atualização automática · ${(sync.scanned||0).toLocaleString('pt-BR')} processos consultados neste ciclo · Última resposta ${fmt(sync.lastSuccess)}`;
  else if(S.lastFullSync)el.textContent='● Coleta nacional concluída em '+fmt(S.lastFullSync.at)+' · Atualização automática ativa';
  else el.textContent='Acervo importado da consulta de 08/10/2026 · Cada cartão mostra sua última consulta · Atualização automática preparada';
}
function populateFilters(){
  const fill=(selector,values,title,value)=>{const el=$(selector);el.innerHTML=`<option value="">${title}</option>`+values.map(v=>`<option value="${e(v)}">${e(v)}</option>`).join('');el.value=value;};
  fill('#filter-uf',[...new Set(S.catalog.map(r=>r.uf).filter(Boolean))].sort(),'Todas as UFs',S.filter.uf);
  fill('#filter-service',[...new Set(S.catalog.flatMap(r=>r.sv||[]))].sort(),'Todos os serviços',S.filter.service);
  $('#filter-owner').innerHTML='<option value="">Todos os responsáveis</option><option value="-">Sem responsável</option>'+S.members.map(m=>`<option value="${e(m.id)}">${e(m.name)}</option>`).join('');$('#filter-owner').value=S.filter.owner;
}
function filtered(rows){const f=S.filter;return rows.filter(r=>{
  if(f.scope==='adpro'&&r.scope?.level!=='in'&&(!r.stage||r.stage==='nova'))return false;
  if(f.scope==='review'&&r.scope?.level!=='review')return false;if(f.scope==='out'&&r.scope?.level!=='out')return false;
  if(f.goal&&(r.goal||inferGoal(r))!==f.goal)return false;
  if(f.uf&&r.uf!==f.uf)return false;if(f.service&&!(r.sv||[]).includes(f.service))return false;
  if(f.owner&&(f.owner==='-'?!!r.ownerId:r.ownerId!==f.owner))return false;
  if(f.deadline){const end=dateTime(r.fim),h=end?(end-Date.now())/3600000:-1;if(h<=0||h>Number(f.deadline))return false;}
  if(f.q){const hay=normalize([r.obj,r.org,r.un,r.cid,r.id,...r.mc||[],...r.sv||[]].join(' '));if(normalize(f.q).split(/\s+/).some(word=>!hay.includes(word)))return false;}
  return true;
});}
function renderMetrics(){
  const live=S.catalog.filter(r=>isLive(r)&&r.scope?.level==='in'&&!r.dup),working=S.catalog.filter(r=>r.stage&&r.stage!=='nova'&&!['declinada','perdida','ganha'].includes(r.stage)),pending=S.tasks.filter(t=>!t.done),urgent=live.filter(r=>dateTime(r.fim)&&dateTime(r.fim)-Date.now()<48*3600000);
  $('#metrics').innerHTML=[[live.length,'Oportunidades abertas','Prazos ainda ativos','⌕'],[working.length,'Em andamento','No funil da equipe','▥'],[pending.length,'Tarefas pendentes',S.member?'Compartilhadas com a equipe':'Entre para gerenciar tarefas','☑'],[urgent.length,'Fecham em 48 horas','Priorize a documentação','◷']].map(([n,label,sub,icon])=>`<div class="metric"><div><div class="label">${label}</div><strong>${n}</strong><small>${sub}</small></div><div class="metric-symbol">${icon}</div></div>`).join('');
  $('#task-count').textContent=pending.length;
}
function card(r){
  const d=deadline(r),tasks=S.tasks.filter(t=>t.opportunity_id===r.id),done=tasks.filter(t=>t.done).length,owner=memberName(r.ownerId),floor=bidMinimum(r,r.quote||{},'total'),floorCount=Object.keys(r.quote?.unitFloors||{}).length,tag=r.mc?.[0]||r.sv?.[0]||'Triagem pendente';
  return `<article class="card" tabindex="0" draggable="${!!S.member}" data-open="${e(r.id)}" aria-label="Abrir ${e(r.org||r.obj)}"><div class="card-head"><span class="tag ${r.mc?.length?'blue':''}">${e(tag)}</span><span class="subtle">${e(r.uf||'BR')}</span></div><div class="card-title">${e(r.obj)}</div><div class="card-org">${e(r.un||r.org)} · ${e(r.cid||'')}</div><div class="card-value">${brl(r.val)}</div><div class="card-meta"><span>▤ ${r.docs?.length||0} anexos</span><span>☑ ${done}/${tasks.length} tarefas</span>${r.dup?'<span title="Possível duplicidade">≃</span>':''}</div><div class="card-foot"><span class="due ${d.class}" title="${e(fmt(r.fim))}">${d.label}</span><span class="avatar" title="${e(owner)}">${r.ownerId?e(initials(owner)):'+'}</span></div>${r.goal?`<div class="card-goal">${e(goalLabel(r.goal))}${r.stage==='declinada'?' · '+e(reasonLabel(r.declineReason)):''}</div>`:''}${r.scope?.level!=='in'?`<div class="scope-warning">${e(r.scope?.level==='out'?'Fora do escopo AD PRO':'Solução integrada — revisar')}</div>`:''}${floor.minimum?`<div class="card-goal"><b>Piso total: ${brl(floor.minimum)}</b></div>`:floorCount?`<div class="card-goal"><b>Pisos definidos: ${floorCount} produto(s)</b></div>`:''}<button class="button secondary small card-bid" data-quick-bid="${e(r.id)}">Preparar lance →</button><select class="card-stage" data-card-stage="${e(r.id)}" aria-label="Mover oportunidade" ${S.member?'':'disabled'}>${stageOptions(r.stage||'nova')}</select></article>`;
}
function renderBoard(){
  const rows=filtered(S.catalog.filter(r=>eligibleForBoard(r))),scroll=$('.board')?.scrollLeft||0;
  $('#content').innerHTML=(S.lastDecision?'<div class="triage-undo"><span>'+e(S.lastDecision.label)+'</span><button class="text-button" data-undo-decision>Desfazer última decisão</button></div>':'')+'<div class="stage-jump" aria-label="Ir para etapa">'+stages.map(([key,label])=>`<button class="button secondary small" data-jump-stage="${key}">${label} <b>${rows.filter(r=>(r.stage||'nova')===key).length}</b></button>`).join('')+'</div><div class="board" aria-label="Quadro Kanban">'+stages.map(([key,label,color])=>{
    const group=rows.filter(r=>(r.stage||'nova')===key),limit=S.columnLimit[key]||30;
    return `<section class="column" data-drop-stage="${key}" style="--stage-color:${color}"><header class="column-header"><div class="column-title"><span class="stage-dot"></span>${label}</div><span class="column-count">${group.length}</span></header><div class="column-cards">${group.slice(0,limit).map(card).join('')||'<div class="empty-column">Nenhuma oportunidade nesta etapa.<br>Arraste um cartão ou altere seu status.</div>'}${group.length>limit?`<button class="button secondary small" data-more="${key}">Mostrar mais ${Math.min(30,group.length-limit)}</button>`:''}</div></section>`;
  }).join('')+'</div><div class="board-footer">'+rows.length+' oportunidades · Use “Preparar lance” no cartão · Etapas acima levam a todas as colunas · '+(S.member?'Alterações compartilhadas com a equipe':'Modo consulta: entre para trabalhar')+'</div>';
  const board=$('.board'),focus=S.boardFocus&&$('[data-drop-stage="'+S.boardFocus+'"]');if(board)board.scrollLeft=focus?focus.offsetLeft-board.offsetLeft:scroll;S.boardFocus=null;if(S.decisionBusy)document.querySelectorAll('[data-undo-decision]').forEach(b=>b.disabled=true);
}
function renderRadar(rows=S.catalog.filter(r=>isLive(r))){const group=filtered(rows);$('#content').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Oportunidade</th><th>Prazo</th><th>Valor estimado</th><th>Etapa</th><th>Documentos</th></tr></thead><tbody>${group.map(r=>`<tr data-open="${e(r.id)}" tabindex="0"><td class="table-object"><b>${e(r.obj)}</b><small>${e(r.org)} · ${e(r.cid)} / ${e(r.uf)}</small></td><td><span class="due ${deadline(r).class}">${deadline(r).label}</span><small class="subtle">${fmt(r.fim)}</small></td><td>${brl(r.val)}</td><td>${stageName(r.stage)}</td><td>${r.docs?.length||0} anexos</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhum resultado com estes filtros.</td></tr>'}</tbody></table></div>`;}
function renderTasks(){
  if(!S.member){$('#content').innerHTML='<div class="empty">Entre para distribuir e acompanhar as tarefas da equipe.<br><button class="button primary" data-action="login">Entrar</button></div>';return;}
  const rows=S.tasks.filter(t=>{const r=S.catalog.find(r=>r.id===t.opportunity_id);return r&&filtered([r]).length;});
  $('#content').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Concluída</th><th>Tarefa</th><th>Oportunidade</th><th>Responsável</th><th>Prazo</th></tr></thead><tbody>${rows.map(t=>{const r=S.catalog.find(r=>r.id===t.opportunity_id);return `<tr><td><input type="checkbox" data-task-toggle="${e(t.id)}" ${t.done?'checked':''} aria-label="Concluir ${e(t.title)}"></td><td>${t.kind==='document'?'▤ ':''}${e(t.title)}</td><td><button class="text-button" data-open="${e(r.id)}">${e(r.org||r.obj).slice(0,90)}</button></td><td>${e(memberName(t.assignee_id))}</td><td>${t.due_at?e(t.due_at.split('-').reverse().join('/')):'Sem prazo'}</td></tr>`;}).join('')||'<tr><td colspan="5" class="empty">Abra uma oportunidade para criar tarefas ou pendências documentais.</td></tr>'}</tbody></table></div>`;
}
function renderTeam(){if(!S.member){$('#content').innerHTML='<div class="empty">Entre para acessar a equipe.<br><button class="button primary" data-action="login">Entrar</button></div>';return;}$('#content').innerHTML='<div class="team-grid">'+S.members.map(m=>`<article class="member-card"><span class="avatar">${e(initials(m.name))}</span><div><b>${e(m.name)}</b><small>${e(m.email)}</small><small>${m.role==='admin'?'Administrador':'Membro da equipe'}</small></div></article>`).join('')+'</div><p class="subtle" style="margin-top:20px">Cada pessoa acessa com sua própria conta. Status, tarefas, comentários, orçamento e estudos de IA são compartilhados. Administradores podem gerar convites no botão acima.</p>';}
function render(){
  const meta={triage:['Triagem rápida','Aceite ou recuse. Simples assim.','Defina o objetivo e o lance mínimo. Aceite para seguir ao Kanban.'],declined:['Recusadas','Decisões e motivos da equipe','Veja o que foi recusado e volte para a triagem quando fizer sentido.'],board:['Quadro Kanban','Seu funil de licitações','Mova oportunidades, distribua tarefas e acompanhe o trabalho da equipe.'],tasks:['Tarefas da equipe','Quem faz o quê','Atividades e documentação com responsáveis e prazos.'],radar:['Radar de oportunidades','Encontre a próxima oportunidade','Pesquise o acervo ativo e abra o edital para avaliar o projeto.'],atas:['Atas vigentes','Inteligência de atas','Atas com fornecedores selecionados: referência para preços e renovações.'],archive:['Encerradas','Histórico de oportunidades','Prazos encerrados ficam fora das novas oportunidades.'],bids:['Lances da equipe','Prepare e acompanhe seus lances','Preço claro, acesso ao portal e registro compartilhado de envio.'],portals:['Portais gratuitos','Acesso aos portais oficiais','Gratuidade verificada e situação real da integração.'],team:['Equipe e convites','Uma operação compartilhada','Acessos individuais, tarefas e decisões visíveis para a equipe.']}[S.view];
  $('#page-name').textContent=meta[0];$('#page-title').textContent=meta[1];$('#page-description').textContent=meta[2];
  document.body.classList.toggle('triage-mode',S.view==='triage');
  document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===S.view));renderMetrics();sourceInfo();
  $('#account').innerHTML=S.member?`<div class="account"><span class="avatar">${e(initials(S.member.name))}</span><span>${e(S.member.name)}</span><button class="text-button" data-action="logout">Sair</button></div>`:'<button class="button secondary small" data-action="login">Entrar na equipe</button>';
  $('#invite-team').hidden=!S.member||S.member.role!=='admin';$('#sync-pncp').hidden=!S.member||S.member.role!=='admin';
  $('#access-guide').innerHTML=S.member?'<b>Como trabalhar:</b> confira edital/TR e defina os pisos → aceite → a equipe prepara o lance no Kanban. As decisões ficam salvas para toda a equipe.':'<b>Consulta — somente leitura.</b> <button class="text-button" data-action="login">Entre na equipe</button> para aceitar, recusar, preparar lances e usar IA.';
  if(S.view==='triage')renderTriage();else if(S.view==='declined')$('#content').innerHTML=declinedPane(filtered(S.catalog));else if(S.view==='board')renderBoard();else if(S.view==='tasks')renderTasks();else if(S.view==='team')renderTeam();else if(S.view==='portals')$('#content').innerHTML=portalsPane();else if(S.view==='bids')renderBids();else renderRadar(S.view==='radar'?S.catalog:S.archive);
}
async function load(silent=false){if(S.loading)return;S.loading=true;try{
  const data=await api(S.member?'/workspace':'/catalog');const previous=new Map(S.catalog.map(r=>[r.id,r]));S.catalog=(data.catalog||[]).map(scopeRecord).map(r=>{const saved=previous.get(r.id);if(saved?.review)r.review=saved.review;return saved&&Number(saved.version)>Number(r.version||0)?{...r,stage:saved.stage,ownerId:saved.ownerId,version:saved.version,notes:saved.notes,quote:saved.quote,goal:saved.goal,declineReason:saved.declineReason}:r;});S.tasks=data.tasks||[];S.bids=data.bids||[];S.members=data.members||[];S.sync=data.sync;S.lastFullSync=data.lastFullSync;
  $('#sync-indicator').textContent='Sincronizado '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
  if(!silent){populateFilters();render();}else if(!$('#detail').open&&!document.activeElement.matches('input,select,textarea'))render();
}catch(err){$('#sync-indicator').textContent='Falha de conexão';if(!silent)toast(err.message,true);}finally{S.loading=false;}}
function openAuth(){
  const register=!!invite;
  $('#auth-content').innerHTML=`<div class="dialog-pad"><button data-close="auth" class="close-button" aria-label="Fechar">×</button><div class="eyebrow">LICITAÇÕES · EQUIPE</div><h2>${register?'Crie seu acesso':'Entre no espaço da equipe'}</h2><p>${register?'Você recebeu um convite. Cadastre sua conta para trabalhar no quadro compartilhado.':'Use sua conta individual para mover cartões, distribuir tarefas e estudar editais com IA. Novos membros entram por convite do administrador.'}</p><form id="auth-form">${register?'<label>Seu nome<input name="name" autocomplete="name" required minlength="2" maxlength="80"></label>':''}<label>E-mail<input name="email" type="email" autocomplete="username" required maxlength="180"></label><label>Senha<input name="password" type="password" autocomplete="${register?'new-password':'current-password'}" required minlength="10" maxlength="200" placeholder="Ao menos 10 caracteres"></label><div class="form-error" id="auth-error"></div><button class="button primary">${register?'Criar conta e abrir quadro':'Entrar'}</button></form>${register?'<button class="text-button" data-action="switch-login">Já tenho conta — entrar</button>':''}</div>`;
  if(!$('#auth').open)$('#auth').showModal();
}
async function openOpportunity(id,tab=S.tab){
  const r=S.catalog.find(r=>r.id===id)||S.archive.find(r=>r.id===id);if(!r)return;
  const request=++S.detailRequest;
  S.detail={opportunity:r,work:{stage:r.stage||'nova',owner_id:r.ownerId,version:r.version||0,goal:r.goal||'',decline_reason:r.declineReason||'',notes:r.notes||'',quote:JSON.stringify(r.quote||{})},tasks:[],comments:[],activity:[],studies:[],bids:[]};S.tab=tab;
  if(S.member)$('#detail-content').innerHTML='<div class="dialog-pad"><button data-close="detail" class="close-button" aria-label="Fechar oportunidade">×</button><div class="loading">Carregando a oportunidade e o trabalho da equipe…</div></div>';else renderDetail();
  if(!$('#detail').open)$('#detail').showModal();
  if(S.member)try{const detail=await api('/opportunities/'+encodeURIComponent(id)+'/detail');if(S.detailRequest!==request||S.detail?.opportunity.id!==id)return;S.detail=detail;if(detail.members)S.members=detail.members;S.detail.opportunity={...scopeRecord(S.detail.opportunity),review:detail.review};renderDetail();}catch(err){toast(err.message,true);}
}
function detailTasks(){return (S.detail.tasks||[]).map(t=>`<div class="task-entry ${t.done?'done':''}"><input type="checkbox" data-task-toggle="${e(t.id)}" ${t.done?'checked':''} aria-label="Concluir ${e(t.title)}"><div><div class="task-title">${t.kind==='document'?'▤ ':''}${e(t.title)}</div><small class="subtle">${e(memberName(t.assignee_id))}${t.due_at?' · '+e(t.due_at.split('-').reverse().join('/')):''}</small></div><div class="task-controls"><button class="text-button" data-edit-task="${e(t.id)}" aria-label="Editar tarefa ${e(t.title)}">Editar</button><button class="text-button" data-archive-task="${e(t.id)}" aria-label="Arquivar tarefa ${e(t.title)}">Arquivar</button></div></div>`).join('')||'<p class="subtle">Nenhuma tarefa criada. Distribua a análise, as cotações e a documentação.</p>';}
function overviewPane(r,w){return `<div class="pane"><div class="notice ${r.scope?.level==='in'?'':'warning'}"><b>${e(r.scope?.level==='in'?'Triagem AD PRO: possível aderência':'Revisão do escopo AD PRO')}</b><br>${e(r.scope?.reason||'Confira o edital antes de considerar compatível.')}</div><h3>Objeto da contratação</h3><div class="object-text">${e(r.obj)}</div>${r.nota?`<div class="panel subtle">${e(r.nota)}</div>`:''}<div class="decision-summary"><b>Objetivo:</b> ${e(goalLabel(w.goal))}${w.stage==='declinada'?`<p><b>Motivo da recusa:</b> ${e(reasonLabel(w.decline_reason))}</p>`:''}</div><details id="work-extra" class="optional-fields" ${(S.drafts[r.id]?.panels?.['work-extra']||S.drafts[r.id]?.notes!==undefined||S.drafts[r.id]?.comment)?'open':''}><summary>Anotações e comentários (opcional)</summary><h3>Anotações da equipe</h3><textarea aria-label="Anotações da equipe" id="work-notes" rows="4" maxlength="8000" placeholder="Decisões, riscos, contato do fornecedor…">${e(w.notes||'')}</textarea><button class="button primary small" data-action="save-work" style="margin-top:8px">Salvar anotações</button><h3>Comentários</h3><form id="comment-form"><textarea aria-label="Comentário para a equipe" name="body" rows="2" maxlength="6000" required placeholder="Compartilhe uma decisão ou atualização…"></textarea><button class="button secondary small" style="margin-top:8px">Publicar comentário</button></form>${(S.detail.comments||[]).map(c=>`<article class="comment"><div class="comment-meta"><span class="avatar">${e(initials(c.name))}</span><b>${e(c.name)}</b><span>${fmt(c.created_at)}</span></div><div class="comment-body">${e(c.body)}</div></article>`).join('')}</details><details class="optional-fields"><summary>Histórico de alterações</summary>${(S.detail.activity||[]).map(a=>`<div class="history"><b>${e(a.name)}</b> · ${e(a.action)} ${e(a.detail||'')}<br>${fmt(a.created_at)}</div>`).join('')||'<p class="subtle">As alterações ficam registradas aqui.</p>'}</details></div>`;}
function documentsPane(r){
  const docs=r.docs||[],preferred=docs.findIndex(d=>/termo de refer|\btr\b/i.test((d.t||'')+' '+(d.n||'')));
  return `<div class="pane"><h3>TR, edital e anexos</h3>${docs.map((d,i)=>`<div class="document"><div class="document-icon">ARQ</div><div class="document-info">${e(d.n||d.t||'Documento')}<small>${e(d.t||'Anexo')} · ${fmt(d.p)}</small></div><div class="document-actions"><a class="button secondary small" href="${e(safeLink(d.u))}" target="_blank" rel="noopener">Abrir</a><a class="button primary small" href="${S.member?'/api/opportunities/'+encodeURIComponent(r.id)+'/download?index='+i:e(safeLink(d.u))}" ${S.member?'download':'target="_blank" rel="noopener"'}>Baixar</a></div></div>`).join('')||'<div class="panel subtle">Os anexos ainda não foram consultados. Clique em “Atualizar prazo e anexos” para buscá-los no PNCP.</div>'}<div class="panel ai"><h3>Estude este projeto com IA</h3><p class="subtle">Escolha um documento para analisar exigências e escopo. A estimativa usa suas premissas de custo e informa quando houver hipóteses.</p><label>Material para análise<select id="study-doc"><option value="-1">Objeto e itens do cadastro</option>${docs.map((d,i)=>`<option value="${i}" ${i===(preferred>=0?preferred:0)?'selected':''}>${e(d.n||d.t||'Documento')}</option>`).join('')}</select></label><details id="study-extra" class="optional-fields" ${S.drafts[r.id]?.panels?.['study-extra']?'open':''}><summary>Premissas e pergunta personalizada (opcional)</summary><label style="margin-top:12px">Premissas de custo<textarea id="study-assumptions" rows="3" maxlength="5000" placeholder="Ex.: equipe R$ 180/h; 2 licenças cotadas a R$ 4.000/ano; implantação estimada em 80 horas; suporte por 12 meses."></textarea></label><label style="margin-top:12px">Pergunta<textarea id="study-question" rows="2" maxlength="3000" placeholder="Quais são os entregáveis, os requisitos de habilitação e os riscos deste projeto?"></textarea></label></details><div class="ai-shortcuts"><button class="button secondary small" data-ai-preset="resumo">Resumir edital</button><button class="button secondary small" data-ai-preset="documentos">Listar documentação</button><button class="button secondary small" data-ai-preset="riscos">Analisar riscos</button></div><div class="ai-actions"><button class="button secondary" data-action="ask-ai">Perguntar à IA</button><button class="button primary" data-action="estimate-ai">Estimar custo do projeto</button></div><div id="ai-result" hidden class="answer" role="status"></div></div><h3>Estudos salvos para a equipe</h3>${(S.detail.studies||[]).map(s=>`<details class="study-entry"><summary><b>${e(s.name)}</b> · ${e(s.question).slice(0,100)}<br><small>${fmt(s.created_at)} · ${e(s.document_name)}</small></summary><div class="answer">${e(s.answer)}</div></details>`).join('')||'<p class="subtle">Os resultados da IA serão salvos aqui e ficarão acessíveis à equipe.</p>'}</div>`;
}
function quotePane(r,w){
  const q=S.drafts[r.id]?.quote||JSON.parse(w.quote||'{}'),fields=[['licenses','Custo-base total do contrato (R$)',0],['hours','Horas de implantação',0],['hourly','Custo por hora (R$)',0],['infra','Infraestrutura (R$)',0],['support','Suporte no período (R$)',0],['other','Outros custos (R$)',0],['contingency','Contingência (%)',0],['tax','Imposto sobre venda (%)',6],['margin','Margem sobre venda (%)',15]];
  return `<div class="pane"><h3>Orçamento e lance mínimo</h3><p class="subtle">Preencha o custo do contrato inteiro, respeitando o período e a unidade do edital. O lance mínimo é calculado com o imposto e a margem definidos abaixo.</p><div class="field-grid">${fields.slice(0,1).map(([key,label,fallback])=>`<label>${label}<input type="number" min="0" step="0.01" data-quote="${key}" value="${e(q[key]??fallback)}"></label>`).join('')}</div><p class="subtle">Modo simples: informe seu custo-base; imposto ${e(q.tax??6)}% e margem ${e(q.margin??15)}% entram no cálculo. ${q.useItems?'Cálculo por itens ativo — confira o detalhamento.':''}</p><details id="quote-extra" class="optional-fields" ${q.useItems||S.drafts[r.id]?.panels?.['quote-extra']?'open':''}><summary>Detalhar custos, tributos e margem (opcional)</summary><div class="field-grid">${fields.slice(1).map(([key,label,fallback])=>`<label>${label}<input type="number" min="0" step="0.01" data-quote="${key}" value="${e(q[key]??fallback)}"></label>`).join('')}</div>${r.it?.length?`<h3>Custos por item</h3><label class="check-label"><input type="checkbox" id="use-item-costs" ${q.useItems?'checked':''}> Usar a soma dos itens no lugar do campo de licenças</label><div class="table-wrap items-table" style="margin-top:12px"><table><thead><tr><th>Descrição / unidade</th><th>Qtd.</th><th>Custo unitário (R$)</th><th>Lance mínimo unitário</th></tr></thead><tbody>${r.it.map((i,index)=>`<tr><td>${e(i.d)}<small class="subtle">${e(i.u||'')} · Referência ${brl(i.vu)}</small></td><td>${i.q??'—'}</td><td><input type="number" min="0" step="0.01" data-item-cost="${index}" value="${e(q.itemCosts?.[index]?.cost??'')}" aria-label="Custo unitário do item ${e(i.n)}"></td><td id="item-bid-${index}">—</td></tr>`).join('')}</tbody></table></div>`:''}</details><div id="quote-result" class="quote-result"></div><div class="ai-actions"><button class="button primary" data-action="save-quote">Salvar preço para a equipe</button><button class="button secondary" data-detail-tab="bids">Preparar lance →</button></div><p class="subtle" style="margin-top:10px">O cálculo orienta seu limite comercial. O envio do lance é feito no portal oficial de disputa.</p></div>`;
}
function tasksPane(){const t=S.editingTask;return `<div class="pane"><h3>Tarefas e checklist documental</h3>${detailTasks()}<div class="ai-actions"><button class="button secondary" data-quick-task="edital">Analisar edital</button><button class="button secondary" data-quick-task="cotacao">Solicitar cotação</button><button class="button secondary" data-quick-task="documentos">Reunir documentos</button></div><details id="task-extra" class="optional-fields" ${t||S.drafts[S.detail.opportunity.id]?.task||S.drafts[S.detail.opportunity.id]?.panels?.['task-extra']?'open':''}><summary>${t?'Editar tarefa':'Tarefa personalizada (opcional)'}</summary><form id="task-form" class="task-form"><input type="hidden" name="taskId" value="${e(t?.id||'')}"><label>Tarefa<input name="title" required maxlength="240" placeholder="Ex.: solicitar cotação / obter certidão" value="${e(t?.title||'')}"></label><label>Responsável<select name="assigneeId">${ownerOptions(t?.assignee_id||S.member?.id)}</select></label><label>Prazo<input name="dueAt" type="date" value="${e(t?.due_at||'')}"></label><label>Tipo<select name="kind"><option value="task">Atividade</option><option value="document" ${t?.kind==='document'?'selected':''}>Documento pendente</option></select></label><button class="button primary" type="submit">${t?'Salvar tarefa':'Adicionar tarefa'}</button>${t?'<button class="text-button" type="button" data-action="cancel-task-edit">Cancelar edição</button>':''}</form></details></div>`;}
function safeLink(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:'#';}catch{return '#';}}
function renderDetail(){
  const {opportunity:r,work:w}=S.detail,d=deadline(r);
  const tabs=[['overview','Resumo e equipe'],['tasks','Tarefas'],['docs','Edital e IA'],['quote','Preço'],['bids','Lances']];
  $('#detail-content').innerHTML=`<header class="detail-header"><div><span class="tag blue">${e(r.mc?.[0]||r.cl||'Oportunidade')}</span><h2>${e(r.un||r.org||'Oportunidade')}</h2><small>${e(r.tit||r.id)} · ${e(r.cid||'')} / ${e(r.uf||'')}</small></div><button data-close="detail" class="close-button" aria-label="Fechar oportunidade">×</button></header><div class="detail-actions"><button class="button secondary" data-detail-tab="docs">1. Ver edital e IA</button><button class="button secondary" data-detail-tab="quote">2. Conferir preço</button><button class="button primary" data-detail-tab="bids">3. Preparar lance →</button><span id="draft-status" role="status"></span></div><div class="detail-body"><div class="detail-main"><div class="tabs">${tabs.map(([key,label])=>`<button data-detail-tab="${key}" class="${S.tab===key?'active':''}">${label}</button>`).join('')}</div>${S.tab==='overview'?overviewPane(r,w):S.tab==='tasks'?tasksPane():S.tab==='docs'?documentsPane(r):S.tab==='bids'?bidPane(r,w,S.detail.bids||[],S.drafts[r.id]?.bid):quotePane(r,w)}</div><aside class="detail-side"><label>Etapa no Kanban<select id="work-stage" ${S.member?'':'disabled'}>${stageOptions(w.stage||'nova')}</select></label><label>Objetivo comercial<select id="work-goal" ${S.member?'':'disabled'}>${goals.map(([id,label])=>`<option value="${id}" ${id===(w.goal||inferGoal(r))?'selected':''}>${e(label)}</option>`).join('')}</select></label><label>Responsável<select id="work-owner" ${S.member?'':'disabled'}>${ownerOptions(w.owner_id)}</select></label><div><h3>Prazo de propostas</h3><div class="fact"><span class="due ${d.class}">${d.label}</span><small>${fmt(r.fim)}</small></div></div><div><h3>Valor estimado</h3><div class="fact"><b>${brl(r.val)}</b></div></div><div class="source-fact"><h3>Última consulta do cartão</h3><div class="fact">${fmt(r.checkedAt)}<small>${e(r.source||'PNCP')}</small></div></div><button class="button secondary small" data-action="refresh-opportunity">↻ Atualizar prazo e anexos</button><div class="portal-fact"><a class="button secondary small" href="${e(safeLink(r.link))}" target="_blank" rel="noopener">Abrir fonte oficial ↗</a>${r.orig?`<a class="button secondary small" style="margin-top:8px" href="${e(safeLink(r.orig))}" target="_blank" rel="noopener">Portal de disputa ↗</a>`:''}</div></aside></div>`;
  restoreDraft();if(S.tab==='quote')updateQuote();if(S.tab==='bids')updateBidPreview(r,w);
}
function quoteValues(){const q={...(S.drafts[S.detail.opportunity.id]?.quote||JSON.parse(S.detail.work.quote||'{}'))};document.querySelectorAll('[data-quote]').forEach(input=>q[input.dataset.quote]=Number(input.value));if($('#use-item-costs'))q.useItems=$('#use-item-costs').checked;if(S.detail.opportunity.it?.length)q.itemCosts=S.detail.opportunity.it.map((i,index)=>({cost:Number($(`[data-item-cost="${index}"]`)?.value)||0,quantity:Number(i.q)||0}));return q;}
function updateQuote(){const q=quoteValues(),result=calculateQuote(q);$('#quote-result').innerHTML=`<div><small>Custo total com contingência</small><strong>${brl(result.cost)}</strong></div><div><small>Lance mínimo total</small><strong>${result.bid===null?'Rever percentuais':result.cost>0?brl(result.bid):'Informe os custos'}</strong></div><div class="wide">Lance = custo ÷ (1 − imposto − margem). ${result.bid!==null&&S.detail.opportunity.val?(result.bid<=S.detail.opportunity.val?'Dentro do valor estimado do cadastro.':'Acima do valor estimado do cadastro.'):'Confirme a unidade e o período antes de cotar.'}</div>`;(q.itemCosts||[]).forEach((i,index)=>{const cell=$('#item-bid-'+index);if(cell)cell.textContent=brl(minimumBid(i.cost,q.tax??6,q.margin??15));});}

function scopeRecord(r){const scope=classifyOpportunity(r);return {...r,scope,mc:scope.mc,sv:scope.sv,cl:scope.cl};}
function renderBids(){if(!S.member){$('#content').innerHTML='<div class="empty">Entre para preparar e acompanhar os lances da equipe.<br><button class="button primary" data-action="login">Entrar</button></div>';return;}const rows=S.bids.filter(b=>{const r=S.catalog.find(r=>r.id===b.opportunity_id);return r&&filtered([r]).length;});$('#content').innerHTML='<div class="notice">Preparado não significa enviado. O envio é feito por você no portal; a confirmação aqui é um registro manual.</div>'+rows.map(b=>'<div class="bid-list-row"><button class="text-button" data-open="'+e(b.opportunity_id)+'">'+e(S.catalog.find(r=>r.id===b.opportunity_id)?.org||b.opportunity_id)+'</button>'+bidRow(b)+'</div>').join('')+(rows.length?'':'<div class="empty">Abra uma oportunidade e clique em “Preparar lance”.</div>');}
function rememberDraft(target){if(!target)return;const inline=target.closest('[data-swipe-card]');if(inline){const id=inline.dataset.swipeCard,d=S.drafts[id]||={};if(target.dataset.inlineInclude)(d.selectedItems||={})[target.dataset.inlineInclude]=target.checked;if(target.dataset.inlineFloor!==undefined)(d.floors||={})[target.dataset.inlineFloor]=target.value;if(target.dataset.inlineAiField)(d.inlineAI||={})[target.dataset.inlineAiField]=target.value;return;}if(!S.detail)return;const id=S.detail.opportunity.id,d=S.drafts[id]||={};
 if(target.id==='work-notes')d.notes=target.value;
 if(target.dataset.quote||target.dataset.itemCost!=null||target.id==='use-item-costs')d.quote=quoteValues();
 if(['study-doc','study-question','study-assumptions'].includes(target.id))d[target.id]=target.value;
 if(target.closest('#comment-form'))d.comment=$('#comment-form [name=body]').value;
 if(target.closest('#task-form'))d.task=Object.fromEntries(new FormData($('#task-form')));
 if(target.closest('#bid-form'))d.bid={...Object.fromEntries(new FormData($('#bid-form'))),acknowledgeUnknownCost:$('#bid-form').elements.acknowledgeUnknownCost.checked};
 draftStatus();
}
function restoreDraft(){const d=S.drafts[S.detail.opportunity.id];if(!d){draftStatus();return;}if($('#work-notes')&&d.notes!==undefined)$('#work-notes').value=d.notes;
 for(const key of ['study-doc','study-question','study-assumptions'])if($('#'+key)&&d[key]!==undefined)$('#'+key).value=d[key];
 if($('#comment-form')&&d.comment!==undefined)$('#comment-form [name=body]').value=d.comment;
 if($('#task-form')&&d.task)for(const [key,value] of Object.entries(d.task)){const input=$('#task-form').elements.namedItem(key);if(input)input.value=value;}
 if($('#ai-result')&&d.lastStudy){$('#ai-result').hidden=false;$('#ai-result').textContent=d.lastStudy;}draftStatus();
}
function draftStatus(){const el=$('#draft-status');if(!el)return;const d=S.drafts[S.detail?.opportunity.id]||{};el.textContent=d.quote||d.notes!==undefined?'Alterações não salvas · rascunho preservado nesta aba':'Trabalho salvo na equipe';}
window.addEventListener('beforeunload',event=>{if(Object.values(S.drafts).some(d=>d.quote||d.notes!==undefined||d.comment||d.task?.title||d.bid?.amount||Object.keys(d.floors||{}).length||Object.keys(d.selectedItems||{}).length)){event.preventDefault();event.returnValue='';}});


function renderTriage(){const focused=document.activeElement?.dataset.inlineFloor,selection=document.activeElement?.selectionStart;const rows=filtered(S.catalog),r=rows.find(r=>r.scope?.level==='in'&&(!r.stage||r.stage==='nova')&&isLive(r)),tab=r?S.inlineTabs[r.id]||'overview':'overview',draft=r?S.drafts[r.id]||{}:{},studies=r?S.inlineData[r.id]?.studies||[]:[];const pane=!r?'':tab==='products'?productsPane(r):tab==='docs'?filesPane(r,S.member,S.inlineDocument[r.id]||0):tab==='ai'?aiPane(r,draft.inlineAI,studies,S.inlineBusy[r.id]):'';$('#content').innerHTML=triagePane(rows,r?(S.triageGoals[r.id]||r.goal||inferGoal(r)):'',S.member,S.lastDecision,tab,pane,r?floorPane(r,draft.floors,draft.selectedItems):'',r?briefPane(r,draft.inlineAI,studies,S.inlineBusy[r.id]||S.autoBusy[r.id]):'');if(r)updateInlineTotals(r);if(focused){const input=$('[data-inline-floor="'+focused+'"]');input?.focus({preventScroll:true});if(input&&selection!=null)input.setSelectionRange(selection,selection);}if(S.decisionBusy)document.querySelectorAll('.swipe-actions button,[data-undo-decision]').forEach(b=>b.disabled=true);if(r&&S.member&&!S.inlineData[r.id]&&!S.inlineLoading[r.id])void loadInline(r.id);if(r&&S.member&&!S.autoReview[r.id])void loadAutomaticReview(r.id);}
async function loadAutomaticReview(id){if(!S.member||S.autoBusy[id])return;S.autoReview[id]=true;S.autoBusy[id]=true;try{const data=await api('/opportunities/'+encodeURIComponent(id)+'/review','POST',{}),r=S.catalog.find(row=>row.id===id);if(data.processing){setTimeout(()=>{delete S.autoReview[id];if(S.view==='triage'&&$('[data-swipe-card]')?.dataset.swipeCard===id)void loadAutomaticReview(id);},6000);return;}if(r)Object.assign(r,data.opportunity?scopeRecord(data.opportunity):{}, {review:data.review});}catch(err){const r=S.catalog.find(row=>row.id===id);if(r&&!r.review)r.review={status:'error',message:err.message,bidRule:{mode:'unknown'},documents:[]};}finally{S.autoBusy[id]=false;if(S.view==='triage')renderTriage();}}
async function loadInline(id){if(!S.member||S.inlineData[id]||S.inlineLoading[id])return;S.inlineLoading[id]=true;try{const data=await api('/opportunities/'+encodeURIComponent(id)+'/detail');S.inlineData[id]=data;const r=S.catalog.find(r=>r.id===id);if(r&&data.review)r.review=data.review;if(r&&Number(data.work.version)>=Number(r.version||0))Object.assign(r,{notes:data.work.notes||'',quote:JSON.parse(data.work.quote||'{}'),goal:data.work.goal||'',declineReason:data.work.decline_reason||'',stage:data.work.stage,ownerId:data.work.owner_id,version:data.work.version});if(S.view==='triage')renderTriage();}catch(err){toast(err.message,true);}finally{S.inlineLoading[id]=false;}}
function floorQuote(r,draft={},selection={}){const quote={...r.quote,unitFloors:{...r.quote?.unitFloors},selectedItems:{...r.quote?.selectedItems,...selection}};if(r.review?.bidRule?.mode!=='item')for(const key of Object.keys(quote.selectedItems))quote.selectedItems[key]=true;for(const [key,value] of Object.entries(draft)){const amount=String(value).trim()?parseAmount(value):null;if(String(value).trim()&&amount===null)throw new Error('Informe pisos maiores que zero, com até quatro casas decimais.');if(key==='total'){if(amount===null)delete quote.minimumTotal;else quote.minimumTotal=amount;}else if(amount===null)delete quote.unitFloors[key];else quote.unitFloors[key]=amount;}const error=floorLimitError(r,quote,true);if(error)throw new Error(error);return quote;}
async function saveInlineFloors(id){if(!needLogin())return;const r=S.catalog.find(r=>r.id===id),draft=S.drafts[id]?.floors,selection=S.drafts[id]?.selectedItems;if(!r||!draft&&!selection){toast('Preencha um piso para salvar.');return;}let quote;try{quote=floorQuote(r,draft,selection);}catch(err){toast(err.message,true);return;}if(await saveWork(r,{quote})){delete S.drafts[id].floors;delete S.drafts[id].selectedItems;delete S.inlineData[id];renderTriage();toast('Mínimos e produtos selecionados salvos para a equipe');}}
async function runInlineStudy(id,mode){if(!needLogin()||S.inlineBusy[id])return;const r=S.catalog.find(r=>r.id===id);if(!r)return;const draft=(S.drafts[id]||={}).inlineAI||={},docs=r.docs||[],preferred=docs.findIndex(d=>/termo de refer|\btr\b/i.test((d.n||'')+' '+(d.t||''))),questions={brief:'Resumo executivo do edital/TR: apresente de forma objetiva o escopo, produtos e entregáveis; quantidade, unidade e período; regras de preço por item/lote/total; vigência e prazo de execução; documentação e requisitos técnicos obrigatórios; portal, prazo e condições da proposta; pagamento, garantias e riscos relevantes. Cite as seções que sustentam cada ponto. Marque como não identificado tudo que não consta no material. Não invente requisitos nem confunda o prazo de proposta com o de execução.',resumo:'Resuma objeto, produtos, unidade e período, prazos e entregáveis do edital. Cite as seções.',documentos:'Liste os documentos de habilitação e requisitos obrigatórios, citando as seções.'};const controls=$('[data-swipe-card]');for(const key of ['documentIndex','question','assumptions']){const input=controls?.querySelector('[data-inline-ai-field="'+key+'"]');if(input)draft[key]=input.value;}const question=questions[mode]||draft.question||'';if(mode==='ask'&&!question.trim()){toast('Digite sua dúvida ou escolha Resumo ou Documentação.',true);$('[data-inline-ai-field="question"]')?.focus();return;}const documentIndex=mode==='brief'?(preferred>=0?preferred:docs.length?0:-1):Number(draft.documentIndex??(preferred>=0?preferred:docs.length?0:-1));S.inlineBusy[id]=true;renderTriage();try{const data=await api('/opportunities/'+encodeURIComponent(id)+'/study','POST',{mode:mode==='estimate'?'estimate':'ask',question,assumptions:mode==='brief'?'':draft.assumptions||'',documentIndex});const answer=data.answer+(data.truncated?'\n\nDocumento longo: análise recebeu um trecho parcial.':'');if(mode==='brief'){draft.brief=answer;draft.briefDocument=data.documentName;}else draft.answer=answer;(S.inlineData[id]||={studies:[]}).studies.unshift({id:data.id,question:mode==='estimate'?'Estimativa de custo':question,answer,document_name:data.documentName,name:S.member.name});toast('Resposta salva para a equipe');}catch(err){if(mode!=='brief')draft.answer=err.message;toast(err.message,true);}finally{S.inlineBusy[id]=false;if(S.view==='triage')renderTriage();}}
function decisionRecord(id){return S.catalog.find(r=>r.id===id)||S.detail?.opportunity.id===id&&S.detail.opportunity;}
function openDecline(id){if(!needLogin())return;const r=decisionRecord(id);if(!r)return;S.declineId=id;$('#decline-title').textContent=r.un||r.org||'Oportunidade';$('#decline-goal').innerHTML=goals.map(([key,label])=>'<option value="'+key+'" '+(key===(S.triageGoals[id]||S.detail?.work?.goal||r.goal||inferGoal(r))?'selected':'')+'>'+e(label)+'</option>').join('');$('#decline-reasons').innerHTML=declineReasons.map(([key,label])=>'<button type="button" class="button secondary" data-decline-reason="'+key+'">'+e(label)+'</button>').join('');if(!$('#decline-dialog').open)$('#decline-dialog').showModal();}
async function decide(id,stage,reason=''){if(S.decisionBusy||!needLogin())return;const r=decisionRecord(id);if(!r)return;const w=S.detail?.opportunity.id===id?S.detail.work:null,previous={stage:w?.stage||r.stage||'nova',goal:w?.goal??r.goal??'',declineReason:w?.decline_reason??r.declineReason??'',ownerId:w?w.owner_id:r.ownerId||null},goal=stage==='declinada'?$('#decline-goal').value:S.triageGoals[id]||r.goal||inferGoal(r),changes={stage,goal,declineReason:reason,ownerId:previous.ownerId||S.member.id};if(stage==='compativel')try{changes.quote=floorQuote(r,S.drafts[id]?.floors,S.drafts[id]?.selectedItems);}catch(err){toast(err.message,true);return;}S.decisionBusy=true;document.querySelectorAll('[data-decline-reason],.swipe-actions button,[data-undo-decision]').forEach(b=>b.disabled=true);try{if(await saveWork(r,changes)){if(changes.quote&&S.drafts[id]){delete S.drafts[id].floors;delete S.drafts[id].selectedItems;}delete S.inlineData[id];S.lastDecision={id,previous,version:r.version,label:stage==='declinada'?'Recusada: '+reasonLabel(reason):'Aceita: '+goalLabel(goal)};$('#decline-dialog').close();if(stage==='compativel'){S.view='board';S.boardFocus='compativel';if($('#detail').open)$('#detail').close();}else if(S.detail?.opportunity.id===id)renderDetail();render();await load(true);toast(stage==='declinada'?'Recusada e motivo salvo para a equipe':'Pisos e objetivo salvos. Oportunidade em Compatíveis no Kanban.');}}finally{S.decisionBusy=false;document.querySelectorAll('[data-decline-reason],.swipe-actions button,[data-undo-decision]').forEach(b=>b.disabled=false);}}
async function undoDecision(){if(S.decisionBusy)return;const last=S.lastDecision,r=last&&S.catalog.find(r=>r.id===last.id);if(!r)return;if(r.version!==last.version){toast('A equipe já alterou esta oportunidade. Abra a ficha para revisar a decisão.',true);return;}if(await saveWork(r,last.previous)){S.lastDecision=null;if(last.previous.stage==='nova')S.view='triage';render();await load();toast('Última decisão desfeita');}}
let gesture=null,suppressSwipeClickUntil=0;
document.addEventListener('pointerdown',event=>{const card=event.target.closest('[data-swipe-card]');if(!card||event.button!==0||event.target.closest('button,a,input,select,textarea,.inline-pane,.tabs,.triage-floors,.tender-brief'))return;gesture={id:card.dataset.swipeCard,card,x:event.clientX,y:event.clientY,pointer:event.pointerId,dx:0};card.setPointerCapture(event.pointerId);});
document.addEventListener('pointermove',event=>{if(!gesture||gesture.pointer!==event.pointerId)return;const dx=event.clientX-gesture.x,dy=event.clientY-gesture.y;if(Math.abs(dy)>Math.abs(dx)&&Math.abs(dy)>20){gesture.card.style.transform='';gesture=null;return;}gesture.dx=dx;if(Math.abs(dx)>10){gesture.card.style.transform='translateX('+Math.max(-140,Math.min(140,dx))+'px) rotate('+dx/25+'deg)';gesture.card.classList.toggle('swipe-yes',dx>65);gesture.card.classList.toggle('swipe-no',dx< -65);}});
document.addEventListener('pointerup',event=>{if(!gesture||gesture.pointer!==event.pointerId)return;const {id,dx,card}=gesture;gesture=null;card.style.transform='';card.classList.remove('swipe-yes','swipe-no');if(Math.abs(dx)>=90){suppressSwipeClickUntil=Date.now()+400;if(dx>0)void decide(id,'compativel');else openDecline(id);}});
document.addEventListener('pointercancel',()=>{if(gesture){gesture.card.style.transform='';gesture.card.classList.remove('swipe-yes','swipe-no');gesture=null;}});
document.addEventListener('click',event=>{if(Date.now()<suppressSwipeClickUntil&&event.target.closest('[data-swipe-card]')){event.preventDefault();event.stopImmediatePropagation();}},true);
document.addEventListener('keydown',event=>{if(event.target.matches('[data-swipe-card]')&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();const id=event.target.dataset.swipeCard;if(event.key==='ArrowRight')void decide(id,'compativel');else openDecline(id);}});
let saveQueue=Promise.resolve();
function saveWork(r,changes={}){const operation=saveQueue.then(()=>persistWork(r,changes));saveQueue=operation.catch(()=>false);return operation;}
async function persistWork(r,changes={}){
  if(!needLogin())return false;const detail=S.detail?.opportunity.id===r.id?S.detail:null,w=detail?.work;
  const payload={stage:w?.stage||r.stage||'nova',ownerId:(w?w.owner_id:r.ownerId)||null,version:w?.version??r.version??0,goal:w?.goal??r.goal??'',declineReason:w?.decline_reason??r.declineReason??'',notes:w?.notes??r.notes??'',quote:w?JSON.parse(w.quote||'{}'):r.quote||{},...changes};
  try{const result=await api('/opportunities/'+encodeURIComponent(r.id),'PATCH',payload);Object.assign(r,{stage:payload.stage,ownerId:payload.ownerId,version:result.version,goal:payload.goal,declineReason:payload.stage==='declinada'?payload.declineReason:'',notes:payload.notes,quote:payload.quote});const canonical=S.catalog.find(row=>row.id===r.id);if(canonical&&canonical!==r)Object.assign(canonical,{stage:r.stage,ownerId:r.ownerId,version:r.version,goal:r.goal,declineReason:r.declineReason,notes:r.notes,quote:r.quote});if(w)Object.assign(w,{stage:payload.stage,owner_id:payload.ownerId,version:result.version,goal:payload.goal,decline_reason:payload.stage==='declinada'?payload.declineReason:'',notes:payload.notes,quote:JSON.stringify(payload.quote)});toast('Salvo para a equipe');renderMetrics();return true;}catch(err){toast(err.message,true);if(err.status===409){await load();if(detail)await openOpportunity(r.id,S.tab);}return false;}
}
async function changeStage(id,stage){const r=S.catalog.find(r=>r.id===id);if(!r)return;if(stage==='declinada'){openDecline(id);render();return;}if(await saveWork(r,{stage}))render();else render();}
async function inviteTeam(){if(!needLogin())return;try{const data=await api('/invites','POST',{});$('#invite-url').value=data.url;$('#invite-dialog').showModal();}catch(err){toast(err.message,true);}}
async function runStudy(estimate){if(!needLogin())return;const result=$('#ai-result'),buttons=[...document.querySelectorAll('[data-action="ask-ai"],[data-action="estimate-ai"]')];buttons.forEach(b=>b.disabled=true);result.hidden=false;result.textContent='Lendo o material e preparando '+(estimate?'a estimativa de custo':'a resposta')+'…';const id=S.detail.opportunity.id;
  try{const data=await api('/opportunities/'+encodeURIComponent(id)+'/study','POST',{mode:estimate?'estimate':'ask',question:$('#study-question').value,assumptions:$('#study-assumptions').value,documentIndex:Number($('#study-doc').value)});if(S.detail?.opportunity.id!==id)return;result.textContent=data.answer+(data.truncated?'\n\nDocumento longo: a análise recebeu um trecho parcial.':'');S.detail.studies.unshift({id:data.id,answer:data.answer,question:estimate?'Estimativa de custo':$('#study-question').value,document_name:data.documentName,name:S.member.name,created_at:new Date().toISOString()});(S.drafts[id]||={}).lastStudy=data.answer;toast('Estudo salvo para a equipe');}catch(err){result.textContent=err.message;toast(err.message,true);}finally{buttons.forEach(b=>b.disabled=false);}}
document.addEventListener('click',async event=>{
  const target=event.target,id=target.closest('[data-swipe-card]')?.dataset.swipeCard;
  const inlineTab=target.closest('[data-inline-tab]');if(inlineTab){if(inlineTab.dataset.inlineTab==='ai'&&inlineTab.closest('.inline-pane')){const d=S.drafts[id]||={};(d.inlineAI||={}).documentIndex=S.inlineDocument[id]||0;}S.inlineTabs[id]=inlineTab.dataset.inlineTab;renderTriage();await loadInline(id);return;}
  if(target.closest('[data-inline-save-floors]')){await saveInlineFloors(id);return;}
  const inlineAI=target.closest('[data-inline-ai]');if(inlineAI){await runInlineStudy(id,inlineAI.dataset.inlineAi);return;}
  const inlineRefresh=target.closest('[data-inline-refresh]');if(inlineRefresh){if(!needLogin())return;inlineRefresh.disabled=true;inlineRefresh.textContent='Consultando PNCP…';try{const data=await api('/opportunities/'+encodeURIComponent(id)+'/refresh','POST',{}),r=S.catalog.find(r=>r.id===id);Object.assign(r,scopeRecord(data.opportunity));delete S.inlineData[id];delete S.autoReview[id];renderTriage();toast('Produtos e anexos oficiais atualizados');}catch(err){toast(err.message,true);inlineRefresh.disabled=false;inlineRefresh.textContent='Tentar consulta novamente';}return;}
  const goal=target.closest('[data-goal-choice]');if(goal){const id=$('[data-swipe-card]')?.dataset.swipeCard;if(id){S.triageGoals[id]=goal.dataset.goalChoice;renderTriage();$('[data-goal-choice="'+goal.dataset.goalChoice+'"]').focus();}return;}
  const accept=target.closest('[data-triage-accept]');if(accept){await decide(accept.dataset.triageAccept,'compativel');return;}
  const decline=target.closest('[data-triage-decline]');if(decline){openDecline(decline.dataset.triageDecline);return;}
  const reason=target.closest('[data-decline-reason]');if(reason){await decide(S.declineId,'declinada',reason.dataset.declineReason);return;}
  if(target.closest('[data-undo-decision]')){await undoDecision();return;}
  const reevaluate=target.closest('[data-reevaluate]');if(reevaluate){const r=S.catalog.find(r=>r.id===reevaluate.dataset.reevaluate);if(r&&await saveWork(r,{stage:'nova',declineReason:''})){S.view='triage';await load();}return;}
  const close=target.closest('[data-close]');if(close){$('#'+close.dataset.close).close();return;}
  const view=target.closest('[data-view]');if(view){S.view=view.dataset.view;if(['archive','atas'].includes(S.view)){if(!needLogin()){S.view='board';return;}try{S.archive=(await api('/archive?kind='+(S.view==='atas'?'ata':'opportunity'))).catalog;}catch(err){toast(err.message,true);}}render();return;}
  const jump=target.closest('[data-jump-stage]');if(jump){const board=$('.board'),column=$('[data-drop-stage="'+jump.dataset.jumpStage+'"]');board.scrollTo({left:column.offsetLeft-board.offsetLeft,behavior:'smooth'});column.querySelector('.column-title').setAttribute('tabindex','-1');column.querySelector('.column-title').focus({preventScroll:true});return;}
  const quick=target.closest('[data-quick-bid]');if(quick){if(!S.member){S.pendingOpen={id:quick.dataset.quickBid,tab:'bids'};openAuth();return;}await openOpportunity(quick.dataset.quickBid,'bids');return;}
  const preset=target.closest('[data-ai-preset]');if(preset){$('#study-question').value={resumo:'Resuma o objeto, entregáveis, quantidades, período, unidade de proposta e prazos. Separe fatos de hipóteses.',documentos:'Liste os documentos de habilitação e os comprovantes exigidos, citando as seções do edital.',riscos:'Quais riscos técnicos, comerciais e exigências podem impedir a participação da AD PRO? Cite o documento.'}[preset.dataset.aiPreset];rememberDraft($('#study-question'));await runStudy(false);return;}
  const copy=target.closest('[data-copy-bid]');if(copy){const bid=(S.detail?.bids||S.bids).find(b=>b.id===copy.dataset.copyBid);try{await navigator.clipboard.writeText(Number(bid.amount).toFixed(4).replace('.',','));toast('Valor copiado: '+Number(bid.amount).toFixed(4).replace('.',','));}catch{toast('Não foi possível copiar. Use o valor mostrado no lance.',true);}return;}
  const report=target.closest('[data-report-bid]');if(report){const bid=(S.detail?.bids||S.bids).find(b=>b.id===report.dataset.reportBid);if(!bid)return;if(S.detail?.opportunity.id!==bid.opportunity_id)await openOpportunity(bid.opportunity_id,'bids');$('#report-bid-id').value=bid.id;$('#report-portal').value=bid.portal_url;$('#report-confirm').checked=false;$('#report-error').textContent='';$('#report-receipt').value='';$('#report-amount').textContent=bidMoney(bid.amount)+' · '+bid.item_label;$('#report-dialog').showModal();return;}
  const quickTask=target.closest('[data-quick-task]');if(quickTask){if(!needLogin())return;const titles={edital:'Analisar edital e TR',cotacao:'Solicitar cotação',documentos:'Reunir documentação de habilitação'},id=S.detail.opportunity.id;quickTask.disabled=true;try{await api('/opportunities/'+encodeURIComponent(id)+'/tasks','POST',{title:titles[quickTask.dataset.quickTask],assigneeId:S.detail.work.owner_id||S.member.id,kind:quickTask.dataset.quickTask==='documentos'?'document':'task'});await load(true);await openOpportunity(id,'tasks');toast('Tarefa criada para a equipe');}catch(err){toast(err.message,true);quickTask.disabled=false;}return;}
  const editTask=target.closest('[data-edit-task]');if(editTask){const t=S.tasks.find(t=>t.id===editTask.dataset.editTask)||S.detail?.tasks.find(t=>t.id===editTask.dataset.editTask);if(!t)return;S.editingTask=t;delete S.drafts[t.opportunity_id]?.task;await openOpportunity(t.opportunity_id,'tasks');$('#task-form [name=title]')?.focus();return;}
  const archiveTask=target.closest('[data-archive-task]');if(archiveTask){const t=S.tasks.find(t=>t.id===archiveTask.dataset.archiveTask)||S.detail?.tasks.find(t=>t.id===archiveTask.dataset.archiveTask);if(!t||!confirm('Arquivar a tarefa “'+t.title+'”? Ela será retirada da lista, com registro no histórico.'))return;try{await api('/tasks/'+t.id,'DELETE',{});S.editingTask=null;await load(true);if(S.detail)await openOpportunity(t.opportunity_id,'tasks');toast('Tarefa arquivada; histórico preservado.');}catch(err){toast(err.message,true);}return;}
  const tab=target.closest('[data-detail-tab]');if(tab){S.tab=tab.dataset.detailTab;renderDetail();return;}
  const more=target.closest('[data-more]');if(more){S.columnLimit[more.dataset.more]=(S.columnLimit[more.dataset.more]||30)+30;renderBoard();return;}
  if(target.closest('#invite-team')||target.closest('[data-action="invite"]')){await inviteTeam();return;}
  if(target.closest('#copy-invite')){try{await navigator.clipboard.writeText($('#invite-url').value);toast('Convite copiado');}catch{$('#invite-url').select();toast('Selecione e copie o link');}return;}
  if(target.closest('#refresh-workspace')){await load();return;}
  if(target.closest('#export-snapshot')){try{const data=await api(S.member?'/workspace':'/catalog'),blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),scope:S.member?'acervo e quadro da equipe':'acervo público',notice:'Exportação do estado atual; checkedAt é a data da consulta oficial de cada registro.',...data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='licitacoes-snapshot-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Snapshot exportado');}catch(err){toast(err.message,true);}return;}
  if(target.closest('#sync-pncp')){if(!needLogin())return;try{const result=await api('/sync','POST',{});toast(result.message);await load();}catch(err){toast(err.message,true);}return;}
  if(target.closest('#clear-filters')||target.closest('#clear-triage-filters')){S.filter={q:'',uf:'',owner:'',service:'',deadline:'',scope:'adpro',goal:''};$('#search').value='';$('#filter-deadline').value='';$('#filter-scope').value='adpro';$('#filter-goal').value='';populateFilters();render();return;}
  const action=target.closest('[data-action]');if(action){
    const kind=action.dataset.action;
    if(kind==='cancel-task-edit'){S.editingTask=null;delete S.drafts[S.detail.opportunity.id]?.task;renderDetail();return;}if(kind==='login'){openAuth();return;}if(kind==='switch-login'){invite=null;history.replaceState(null,'',location.pathname);openAuth();return;}
    if(kind==='logout'){await api('/logout','POST',{});S.member=null;S.detail=null;S.drafts={};S.lastDecision=null;S.triageGoals={};S.inlineData={};S.inlineTabs={};$('#detail').close();await load();return;}
    if(kind==='ask-ai'&&!$('#study-question').value.trim()){$('#study-extra').open=true;$('#study-question').focus();return;}
    if(kind==='ask-ai'||kind==='estimate-ai'){await runStudy(kind==='estimate-ai');return;}
    if(kind==='save-work'){if(await saveWork(S.detail.opportunity,{notes:$('#work-notes').value})){delete S.drafts[S.detail.opportunity.id]?.notes;draftStatus();}return;}
    if(kind==='save-quote'){if(await saveWork(S.detail.opportunity,{quote:quoteValues()})){delete S.drafts[S.detail.opportunity.id]?.quote;draftStatus();}return;}
    if(kind==='refresh-opportunity'){if(!needLogin())return;action.disabled=true;action.textContent='Consultando PNCP…';const id=S.detail.opportunity.id;try{const data=await api('/opportunities/'+encodeURIComponent(id)+'/refresh','POST',{});if(S.detail?.opportunity.id===id){S.detail.opportunity=data.opportunity;renderDetail();}toast('Prazos, documentos e itens atualizados');await load(true);}catch(err){toast(err.message,true);action.disabled=false;action.textContent='↻ Atualizar prazo e anexos';}return;}
  }
  const open=target.closest('[data-open]');if(open&&!target.closest('select,input,a'))await openOpportunity(open.dataset.open,'overview');
});
document.addEventListener('keydown',event=>{if(['Enter',' '].includes(event.key)&&event.target.matches('.card,tr[data-open]')){event.preventDefault();openOpportunity(event.target.dataset.open,'overview');}});
document.addEventListener('toggle',event=>{const t=event.target;if(S.detail&&t.isConnected&&['work-extra','study-extra','quote-extra','task-extra'].includes(t.id)){const d=S.drafts[S.detail.opportunity.id]||={};(d.panels||={})[t.id]=t.open;}},true);
document.addEventListener('input',event=>{const t=event.target;if(t.id==='search'){S.filter.q=t.value;render();}rememberDraft(t);if(t.dataset.inlineFloor!==undefined){const r=S.catalog.find(r=>r.id===t.closest('[data-swipe-card]')?.dataset.swipeCard);if(r)updateInlineTotals(r);}if(t.dataset.quote||t.dataset.itemCost!=null)updateQuote();if(t.closest('#bid-form'))updateBidPreview(S.detail.opportunity,S.detail.work);});
document.addEventListener('change',async event=>{const t=event.target,map={'filter-uf':'uf','filter-service':'service','filter-owner':'owner','filter-deadline':'deadline','filter-scope':'scope','filter-goal':'goal'};
  if(t.matches('[data-inline-include]')){renderTriage();return;}
  if(t.matches('[data-inline-document]')){const id=t.closest('[data-swipe-card]').dataset.swipeCard;S.inlineDocument[id]=Number(t.value);renderTriage();return;}
  if(t.matches('[data-triage-goal]')){const id=$('[data-swipe-card]')?.dataset.swipeCard;if(id)S.triageGoals[id]=t.value;return;}
  if(map[t.id]){S.filter[map[t.id]]=t.value;render();return;}
  if(t.dataset.cardStage){await changeStage(t.dataset.cardStage,t.value);return;}
  if(['work-stage','work-owner','work-goal'].includes(t.id)){if(t.id==='work-stage'&&t.value==='declinada'){openDecline(S.detail.opportunity.id);t.value=S.detail.work.stage;return;}await saveWork(S.detail.opportunity,{stage:$('#work-stage').value,goal:$('#work-goal').value,ownerId:$('#work-owner').value||null});await load(true);return;}
  rememberDraft(t);if(t.id==='use-item-costs')updateQuote();
  if(t.id==='bid-portal-choice'){if(t.value)$('#bid-portal').value=t.value;rememberDraft($('#bid-portal'));}if(t.closest('#bid-form'))updateBidPreview(S.detail.opportunity,S.detail.work);
  if(t.dataset.taskToggle){if(!needLogin()){t.checked=!t.checked;return;}try{await api('/tasks/'+t.dataset.taskToggle,'PATCH',{done:t.checked});await load(true);if(S.detail&&$('#detail').open)await openOpportunity(S.detail.opportunity.id,S.tab);else render();}catch(err){t.checked=!t.checked;toast(err.message,true);}}
});
document.addEventListener('submit',async event=>{const form=event.target;if(!['auth-form','task-form','comment-form','bid-form','report-form'].includes(form.id))return;event.preventDefault();const button=form.querySelector('button[type=submit]')||form.querySelector('button'),body=Object.fromEntries(new FormData(form));
  if(form.id!=='auth-form'&&!needLogin())return;button.disabled=true;
  try{
    if(form.id==='auth-form'){const data=await api(invite?'/register':'/login','POST',{...body,invite});S.member=data.member;invite=null;history.replaceState(null,'',location.pathname);$('#auth').close();await load();if(S.pendingOpen){const pending=S.pendingOpen;S.pendingOpen=null;await openOpportunity(pending.id,pending.tab);}else if(S.detail)await openOpportunity(S.detail.opportunity.id,S.tab);toast('Bem-vindo ao espaço da equipe');}
    else if(form.id==='bid-form'){const id=S.detail.opportunity.id;await api('/opportunities/'+encodeURIComponent(id)+'/bids','POST',{...body,id:crypto.randomUUID(),version:S.detail.work.version,amount:parseAmount(body.amount),acknowledgeUnknownCost:form.elements.acknowledgeUnknownCost.checked});delete S.drafts[id]?.bid;await load(true);if(S.detail?.opportunity.id===id&&$('#detail').open)await openOpportunity(id,S.tab);toast('Preparado. Copie o valor e envie no portal oficial.');}
    else if(form.id==='report-form'){const id=S.detail.opportunity.id;await api('/bids/'+body.bidId+'/report','POST',{confirmSent:$('#report-confirm').checked,portalUrl:body.portalUrl,receipt:body.receipt,version:S.detail.work.version});$('#report-dialog').close();await load(true);if(S.detail?.opportunity.id===id&&$('#detail').open)await openOpportunity(id,S.tab);toast('Envio informado por você e registrado para a equipe.');}
    else{const id=S.detail.opportunity.id;if(form.id==='task-form'&&body.taskId)await api('/tasks/'+body.taskId,'PATCH',body);else await api('/opportunities/'+encodeURIComponent(id)+(form.id==='task-form'?'/tasks':'/comments'),'POST',body);if(form.id==='task-form'){S.editingTask=null;delete S.drafts[id]?.task;}else delete S.drafts[id]?.comment;await load(true);await openOpportunity(id,S.tab);toast(form.id==='task-form'?'Tarefa salva':'Comentário publicado');}
  }catch(err){if(form.id==='auth-form')$('#auth-error').textContent=err.message;else if(form.id==='bid-form')$('#bid-error').textContent=err.message;else if(form.id==='report-form')$('#report-error').textContent=err.message;else toast(err.message,true);}finally{button.disabled=false;}
});
document.addEventListener('dragstart',event=>{const card=event.target.closest('.card');if(!card||!S.member)return;dragId=card.dataset.open;event.dataTransfer.setData('text/plain',dragId);event.dataTransfer.effectAllowed='move';card.classList.add('dragging');});
document.addEventListener('dragover',event=>{const column=event.target.closest('[data-drop-stage]');if(column&&dragId){event.preventDefault();column.classList.add('drop-target');}});
document.addEventListener('dragleave',event=>{const column=event.target.closest('[data-drop-stage]');if(column&&!column.contains(event.relatedTarget))column.classList.remove('drop-target');});
document.addEventListener('drop',async event=>{const column=event.target.closest('[data-drop-stage]');if(column&&dragId){event.preventDefault();const id=dragId;dragId=null;await changeStage(id,column.dataset.dropStage);}});
document.addEventListener('dragend',()=>{dragId=null;document.querySelectorAll('.dragging,.drop-target').forEach(el=>el.classList.remove('dragging','drop-target'));});
$('#detail').addEventListener('close',()=>{S.detail=null;render();});
window.addEventListener('hashchange',()=>{invite=new URLSearchParams(location.hash.slice(1)).get('invite');if(invite)openAuth();});
async function start(){try{S.member=(await api('/me')).member;await load();if(invite)openAuth();}catch(err){$('#content').innerHTML='<div class="empty">Não foi possível carregar o quadro. Use o botão de sincronizar para tentar novamente.</div>';toast(err.message,true);}}
setInterval(async()=>{if(document.hidden||polling)return;polling=true;try{await load(true);}finally{polling=false;}},20000);
start();
