import {stages,escape as e,normalize,dateTime,isLive,eligibleForBoard,minimumBid,calculateQuote} from './core.js';
const $=s=>document.querySelector(s),brl=v=>v==null||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const fmt=s=>dateTime(s)?.toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'})||'Sem data';
const initials=name=>String(name||'?').split(/\s+/).slice(0,2).map(w=>w[0]).join('').toUpperCase();
const S={member:null,members:[],catalog:[],tasks:[],view:'board',detail:null,tab:'overview',sync:null,lastFullSync:null,filter:{q:'',uf:'',owner:'',service:'',deadline:''},columnLimit:{},archive:[],loading:false};
let invite=new URLSearchParams(location.hash.slice(1)).get('invite');
let toastTimer,dragId,polling=false;
async function api(path,method='GET',body){
  const res=await fetch('/api'+path,{method,credentials:'same-origin',headers:body?{'content-type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});
  const data=await res.json().catch(()=>({}));if(!res.ok){const error=new Error(data.error||'Falha na conexão.');error.status=res.status;throw error;}return data;
}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className='toast'+(error?' error':'');el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,error?7500:3500);}
function needLogin(){if(S.member)return true;openAuth();return false;}
const stageName=s=>stages.find(([key])=>key===s)?.[1]||'Novas';
const memberName=id=>S.members.find(m=>m.id===id)?.name||'Sem responsável';
const ownerOptions=(selected='',empty='Sem responsável')=>'<option value="">'+empty+'</option>'+S.members.map(m=>`<option value="${e(m.id)}" ${m.id===selected?'selected':''}>${e(m.name)}</option>`).join('');
const stageOptions=selected=>stages.map(([key,label])=>`<option value="${key}" ${key===selected?'selected':''}>${label}</option>`).join('');
function deadline(r){const end=dateTime(r.fim);if(!end)return {label:'Sem prazo informado',class:''};const h=(end-Date.now())/3600000;if(h<=0)return {label:'Prazo encerrado',class:'urgent'};return {label:h<24?'Fecha em '+Math.max(1,Math.ceil(h))+'h':'Fecha em '+Math.ceil(h/24)+' dias',class:h<48?'urgent':h<168?'soon':''};}
function sourceInfo(){
  const sync=S.sync,el=$('#source-info');el.className='source-info'+(sync?.error?' error':'');
  if(sync?.error)el.textContent='Última coleta encontrou uma falha: '+sync.error+' · Retomada automática na próxima execução.';
  else if(sync?.cycleStarted)el.textContent=`● PNCP em atualização automática · ${(sync.scanned||0).toLocaleString('pt-BR')} processos consultados neste ciclo · Última resposta ${fmt(sync.lastSuccess)}`;
  else if(S.lastFullSync)el.textContent='● Coleta nacional concluída em '+fmt(S.lastFullSync.at)+' · Atualização automática ativa';
  else el.textContent='Acervo importado da consulta de 08/10/2026 · Cada cartão mostra sua última consulta · Atualização automática preparada';
}
function populateFilters(){
  const fill=(selector,values,title,value)=>{const el=$(selector);el.innerHTML=`<option value="">${title}</option>`+values.map(v=>`<option value="${e(v)}">${e(v)}</option>`).join('');el.value=value;};
  fill('#filter-uf',[...new Set(S.catalog.map(r=>r.uf).filter(Boolean))].sort(),'Todas as UFs',S.filter.uf);
  fill('#filter-service',[...new Set(S.catalog.flatMap(r=>r.sv||[]))].sort(),'Todos os serviços',S.filter.service);
  $('#filter-owner').innerHTML='<option value="">Todos os responsáveis</option><option value="-">Sem responsável</option>'+S.members.map(m=>`<option value="${e(m.id)}">${e(m.name)}</option>`).join('');$('#filter-owner').value=S.filter.owner;
}
function filtered(rows){const f=S.filter;return rows.filter(r=>{
  if(f.uf&&r.uf!==f.uf)return false;if(f.service&&!(r.sv||[]).includes(f.service))return false;
  if(f.owner&&(f.owner==='-'?!!r.ownerId:r.ownerId!==f.owner))return false;
  if(f.deadline){const end=dateTime(r.fim),h=end?(end-Date.now())/3600000:-1;if(h<=0||h>Number(f.deadline))return false;}
  if(f.q){const hay=normalize([r.obj,r.org,r.un,r.cid,r.id,...r.mc||[],...r.sv||[]].join(' '));if(normalize(f.q).split(/\s+/).some(word=>!hay.includes(word)))return false;}
  return true;
});}
function renderMetrics(){
  const live=S.catalog.filter(r=>isLive(r)&&!r.dup),working=S.catalog.filter(r=>r.stage&&r.stage!=='nova'&&!['declinada','perdida','ganha'].includes(r.stage)),pending=S.tasks.filter(t=>!t.done),urgent=live.filter(r=>dateTime(r.fim)&&dateTime(r.fim)-Date.now()<48*3600000);
  $('#metrics').innerHTML=[[live.length,'Oportunidades abertas','Prazos ainda ativos','⌕'],[working.length,'Em andamento','No funil da equipe','▥'],[pending.length,'Tarefas pendentes',S.member?'Compartilhadas com a equipe':'Entre para gerenciar tarefas','☑'],[urgent.length,'Fecham em 48 horas','Priorize a documentação','◷']].map(([n,label,sub,icon])=>`<div class="metric"><div><div class="label">${label}</div><strong>${n}</strong><small>${sub}</small></div><div class="metric-symbol">${icon}</div></div>`).join('');
  $('#task-count').textContent=pending.length;
}
function card(r){
  const d=deadline(r),tasks=S.tasks.filter(t=>t.opportunity_id===r.id),done=tasks.filter(t=>t.done).length,owner=memberName(r.ownerId),tag=r.mc?.[0]||r.sv?.[0]||'Triagem pendente';
  return `<article class="card" tabindex="0" draggable="${!!S.member}" data-open="${e(r.id)}" aria-label="Abrir ${e(r.org||r.obj)}"><div class="card-head"><span class="tag ${r.mc?.length?'blue':''}">${e(tag)}</span><span class="subtle">${e(r.uf||'BR')}</span></div><div class="card-title">${e(r.obj)}</div><div class="card-org">${e(r.un||r.org)} · ${e(r.cid||'')}</div><div class="card-value">${brl(r.val)}</div><div class="card-meta"><span>▤ ${r.docs?.length||0} anexos</span><span>☑ ${done}/${tasks.length} tarefas</span>${r.dup?'<span title="Possível duplicidade">≃</span>':''}</div><div class="card-foot"><span class="due ${d.class}" title="${e(fmt(r.fim))}">${d.label}</span><span class="avatar" title="${e(owner)}">${r.ownerId?e(initials(owner)):'+'}</span></div><select class="card-stage" data-card-stage="${e(r.id)}" aria-label="Mover oportunidade">${stageOptions(r.stage||'nova')}</select></article>`;
}
function renderBoard(){
  const rows=filtered(S.catalog.filter(r=>eligibleForBoard(r)));
  $('#content').innerHTML='<div class="board" aria-label="Quadro Kanban">'+stages.map(([key,label,color])=>{
    const group=rows.filter(r=>(r.stage||'nova')===key),limit=S.columnLimit[key]||30;
    return `<section class="column" data-drop-stage="${key}" style="--stage-color:${color}"><header class="column-header"><div class="column-title"><span class="stage-dot"></span>${label}</div><span class="column-count">${group.length}</span></header><div class="column-cards">${group.slice(0,limit).map(card).join('')||'<div class="empty-column">Nenhuma oportunidade nesta etapa.<br>Arraste um cartão ou altere seu status.</div>'}${group.length>limit?`<button class="button secondary small" data-more="${key}">Mostrar mais ${Math.min(30,group.length-limit)}</button>`:''}</div></section>`;
  }).join('')+'</div><div class="board-footer">'+rows.length+' oportunidades · Arraste os cartões entre colunas ou use o status no cartão · Alterações sincronizadas entre usuários</div>';
}
function renderRadar(rows=S.catalog){const group=filtered(rows);$('#content').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Oportunidade</th><th>Prazo</th><th>Valor estimado</th><th>Etapa</th><th>Documentos</th></tr></thead><tbody>${group.map(r=>`<tr data-open="${e(r.id)}" tabindex="0"><td class="table-object"><b>${e(r.obj)}</b><small>${e(r.org)} · ${e(r.cid)} / ${e(r.uf)}</small></td><td><span class="due ${deadline(r).class}">${deadline(r).label}</span><small class="subtle">${fmt(r.fim)}</small></td><td>${brl(r.val)}</td><td>${stageName(r.stage)}</td><td>${r.docs?.length||0} anexos</td></tr>`).join('')||'<tr><td colspan="5" class="empty">Nenhum resultado com estes filtros.</td></tr>'}</tbody></table></div>`;}
function renderTasks(){
  if(!S.member){$('#content').innerHTML='<div class="empty">Entre para distribuir e acompanhar as tarefas da equipe.<br><button class="button primary" data-action="login">Entrar</button></div>';return;}
  const rows=S.tasks.filter(t=>{const r=S.catalog.find(r=>r.id===t.opportunity_id);return r&&filtered([r]).length;});
  $('#content').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Concluída</th><th>Tarefa</th><th>Oportunidade</th><th>Responsável</th><th>Prazo</th></tr></thead><tbody>${rows.map(t=>{const r=S.catalog.find(r=>r.id===t.opportunity_id);return `<tr><td><input type="checkbox" data-task-toggle="${e(t.id)}" ${t.done?'checked':''} aria-label="Concluir ${e(t.title)}"></td><td>${t.kind==='document'?'▤ ':''}${e(t.title)}</td><td><button class="text-button" data-open="${e(r.id)}">${e(r.org||r.obj).slice(0,90)}</button></td><td>${e(memberName(t.assignee_id))}</td><td>${t.due_at?e(t.due_at.split('-').reverse().join('/')):'Sem prazo'}</td></tr>`;}).join('')||'<tr><td colspan="5" class="empty">Abra uma oportunidade para criar tarefas ou pendências documentais.</td></tr>'}</tbody></table></div>`;
}
function renderTeam(){if(!S.member){$('#content').innerHTML='<div class="empty">Entre para acessar a equipe.<br><button class="button primary" data-action="login">Entrar</button></div>';return;}$('#content').innerHTML='<div class="team-grid">'+S.members.map(m=>`<article class="member-card"><span class="avatar">${e(initials(m.name))}</span><div><b>${e(m.name)}</b><small>${e(m.email)}</small><small>${m.role==='admin'?'Administrador':'Membro da equipe'}</small></div></article>`).join('')+'</div><p class="subtle" style="margin-top:20px">Cada pessoa acessa com sua própria conta. Status, tarefas, comentários, orçamento e estudos de IA são compartilhados. Administradores podem gerar convites no botão acima.</p>';}
function render(){
  const meta={board:['Quadro Kanban','Seu funil de licitações','Mova oportunidades, distribua tarefas e acompanhe o trabalho da equipe.'],tasks:['Tarefas da equipe','Quem faz o quê','Atividades e documentação com responsáveis e prazos.'],radar:['Radar de oportunidades','Encontre a próxima oportunidade','Pesquise o acervo ativo e abra o edital para avaliar o projeto.'],atas:['Atas vigentes','Inteligência de atas','Atas com fornecedores selecionados: referência para preços e renovações.'],archive:['Encerradas','Histórico de oportunidades','Prazos encerrados ficam fora das novas oportunidades.'],team:['Equipe e convites','Uma operação compartilhada','Acessos individuais, tarefas e decisões visíveis para a equipe.']}[S.view];
  $('#page-name').textContent=meta[0];$('#page-title').textContent=meta[1];$('#page-description').textContent=meta[2];
  document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===S.view));renderMetrics();sourceInfo();
  $('#account').innerHTML=S.member?`<div class="account"><span class="avatar">${e(initials(S.member.name))}</span><span>${e(S.member.name)}</span><button class="text-button" data-action="logout">Sair</button></div>`:'<button class="button secondary small" data-action="login">Entrar na equipe</button>';
  $('#invite-team').hidden=!!S.member&&S.member.role!=='admin';$('#sync-pncp').hidden=!!S.member&&S.member.role!=='admin';
  if(S.view==='board')renderBoard();else if(S.view==='tasks')renderTasks();else if(S.view==='team')renderTeam();else renderRadar(S.view==='radar'?S.catalog:S.archive);
}
async function load(silent=false){if(S.loading)return;S.loading=true;try{
  const data=await api(S.member?'/workspace':'/catalog');S.catalog=data.catalog||[];S.tasks=data.tasks||[];S.members=data.members||[];S.sync=data.sync;S.lastFullSync=data.lastFullSync;
  $('#sync-indicator').textContent='Sincronizado '+new Date().toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'});
  if(!silent){populateFilters();render();}else if(!$('#detail').open&&!document.activeElement.matches('input,select,textarea'))render();
}catch(err){$('#sync-indicator').textContent='Falha de conexão';if(!silent)toast(err.message,true);}finally{S.loading=false;}}
function openAuth(){
  const register=!!invite;
  $('#auth-content').innerHTML=`<div class="dialog-pad"><button data-close="auth" class="close-button" aria-label="Fechar">×</button><div class="eyebrow">LICITAÇÕES · EQUIPE</div><h2>${register?'Crie seu acesso':'Entre no espaço da equipe'}</h2><p>${register?'Você recebeu um convite. Cadastre sua conta para trabalhar no quadro compartilhado.':'Use sua conta individual para mover cartões, distribuir tarefas e estudar editais com IA. Novos membros entram por convite do administrador.'}</p><form id="auth-form">${register?'<label>Seu nome<input name="name" autocomplete="name" required minlength="2" maxlength="80"></label>':''}<label>E-mail<input name="email" type="email" autocomplete="username" required maxlength="180"></label><label>Senha<input name="password" type="password" autocomplete="${register?'new-password':'current-password'}" required minlength="10" maxlength="200" placeholder="Ao menos 10 caracteres"></label><div class="form-error" id="auth-error"></div><button class="button primary">${register?'Criar conta e abrir quadro':'Entrar'}</button></form></div>`;
  if(!$('#auth').open)$('#auth').showModal();
}
async function openOpportunity(id,tab=S.tab){
  const r=S.catalog.find(r=>r.id===id)||S.archive.find(r=>r.id===id);if(!r)return;
  S.detail={opportunity:r,work:{stage:r.stage||'nova',owner_id:r.ownerId,version:r.version||0,notes:r.notes||'',quote:JSON.stringify(r.quote||{})},tasks:[],comments:[],activity:[],studies:[]};S.tab=tab;
  if(S.member)$('#detail-content').innerHTML='<div class="dialog-pad"><button data-close="detail" class="close-button" aria-label="Fechar oportunidade">×</button><div class="loading">Carregando a oportunidade e o trabalho da equipe…</div></div>';else renderDetail();
  if(!$('#detail').open)$('#detail').showModal();
  if(S.member)try{const detail=await api('/opportunities/'+encodeURIComponent(id)+'/detail');if(S.detail?.opportunity.id!==id)return;S.detail=detail;if(detail.members)S.members=detail.members;renderDetail();}catch(err){toast(err.message,true);}
}
function detailTasks(){return (S.detail.tasks||[]).map(t=>`<div class="task-entry ${t.done?'done':''}"><input type="checkbox" data-task-toggle="${e(t.id)}" ${t.done?'checked':''} aria-label="Concluir ${e(t.title)}"><div><div class="task-title">${t.kind==='document'?'▤ ':''}${e(t.title)}</div><small class="subtle">${e(memberName(t.assignee_id))}${t.due_at?' · '+e(t.due_at.split('-').reverse().join('/')):''}</small></div></div>`).join('')||'<p class="subtle">Nenhuma tarefa criada. Distribua a análise, as cotações e a documentação.</p>';}
function overviewPane(r,w){return `<div class="pane"><h3>Objeto da contratação</h3><div class="object-text">${e(r.obj)}</div>${r.nota?`<div class="panel subtle">${e(r.nota)}</div>`:''}<h3>Anotações da equipe</h3><textarea id="work-notes" rows="4" maxlength="8000" placeholder="Decisões, riscos, contato do fornecedor…">${e(w.notes||'')}</textarea><button class="button primary small" data-action="save-work" style="margin-top:8px">Salvar anotações</button><h3>Comentários</h3><form id="comment-form"><textarea name="body" rows="2" maxlength="6000" required placeholder="Compartilhe uma decisão ou atualização…"></textarea><button class="button secondary small" style="margin-top:8px">Publicar comentário</button></form>${(S.detail.comments||[]).map(c=>`<article class="comment"><div class="comment-meta"><span class="avatar">${e(initials(c.name))}</span><b>${e(c.name)}</b><span>${fmt(c.created_at)}</span></div><div class="comment-body">${e(c.body)}</div></article>`).join('')}<h3>Histórico</h3>${(S.detail.activity||[]).map(a=>`<div class="history"><b>${e(a.name)}</b> · ${e(a.action)} ${e(a.detail||'')}<br>${fmt(a.created_at)}</div>`).join('')||'<p class="subtle">As alterações ficam registradas aqui.</p>'}</div>`;}
function documentsPane(r){
  const docs=r.docs||[],preferred=docs.findIndex(d=>/termo de refer|\btr\b/i.test((d.t||'')+' '+(d.n||'')));
  return `<div class="pane"><h3>TR, edital e anexos</h3>${docs.map((d,i)=>`<div class="document"><div class="document-icon">ARQ</div><div class="document-info">${e(d.n||d.t||'Documento')}<small>${e(d.t||'Anexo')} · ${fmt(d.p)}</small></div><div class="document-actions"><a class="button secondary small" href="${e(safeLink(d.u))}" target="_blank" rel="noopener">Abrir</a><a class="button primary small" href="${S.member?'/api/opportunities/'+encodeURIComponent(r.id)+'/download?index='+i:e(safeLink(d.u))}" ${S.member?'download':'target="_blank" rel="noopener"'}>Baixar</a></div></div>`).join('')||'<div class="panel subtle">Os anexos ainda não foram consultados. Clique em “Atualizar prazo e anexos” para buscá-los no PNCP.</div>'}<div class="panel ai"><h3>Estude este projeto com IA</h3><p class="subtle">Escolha um documento para analisar exigências e escopo. A estimativa usa suas premissas de custo e informa quando houver hipóteses.</p><label>Material para análise<select id="study-doc"><option value="-1">Objeto e itens do cadastro</option>${docs.map((d,i)=>`<option value="${i}" ${i===(preferred>=0?preferred:0)?'selected':''}>${e(d.n||d.t||'Documento')}</option>`).join('')}</select></label><label style="margin-top:12px">Premissas de custo<textarea id="study-assumptions" rows="3" maxlength="5000" placeholder="Ex.: equipe R$ 180/h; 2 licenças cotadas a R$ 4.000/ano; implantação estimada em 80 horas; suporte por 12 meses."></textarea></label><label style="margin-top:12px">Pergunta<textarea id="study-question" rows="2" maxlength="3000" placeholder="Quais são os entregáveis, os requisitos de habilitação e os riscos deste projeto?"></textarea></label><div class="ai-actions"><button class="button secondary" data-action="ask-ai">Perguntar à IA</button><button class="button primary" data-action="estimate-ai">Estimar custo do projeto</button></div><div id="ai-result" hidden class="answer"></div></div><h3>Estudos salvos para a equipe</h3>${(S.detail.studies||[]).map(s=>`<details class="study-entry"><summary><b>${e(s.name)}</b> · ${e(s.question).slice(0,100)}<br><small>${fmt(s.created_at)} · ${e(s.document_name)}</small></summary><div class="answer">${e(s.answer)}</div></details>`).join('')||'<p class="subtle">Os resultados da IA serão salvos aqui e ficarão acessíveis à equipe.</p>'}</div>`;
}
function quotePane(r,w){
  const q=JSON.parse(w.quote||'{}'),fields=[['licenses','Licenças / assinaturas (R$)',0],['hours','Horas de implantação',0],['hourly','Custo por hora (R$)',0],['infra','Infraestrutura (R$)',0],['support','Suporte no período (R$)',0],['other','Outros custos (R$)',0],['contingency','Contingência (%)',0],['tax','Imposto sobre venda (%)',6],['margin','Margem sobre venda (%)',15]];
  return `<div class="pane"><h3>Orçamento e lance mínimo</h3><p class="subtle">Preencha o custo do contrato inteiro, respeitando o período e a unidade do edital. O lance mínimo é calculado com o imposto e a margem definidos abaixo.</p><div class="field-grid">${fields.map(([key,label,fallback])=>`<label>${label}<input type="number" min="0" step="0.01" data-quote="${key}" value="${e(q[key]??fallback)}"></label>`).join('')}</div>${r.it?.length?`<h3>Custos por item</h3><label class="check-label"><input type="checkbox" id="use-item-costs" ${q.useItems?'checked':''}> Usar a soma dos itens no lugar do campo de licenças</label><div class="table-wrap items-table" style="margin-top:12px"><table><thead><tr><th>Descrição / unidade</th><th>Qtd.</th><th>Custo unitário (R$)</th><th>Lance mínimo unitário</th></tr></thead><tbody>${r.it.map((i,index)=>`<tr><td>${e(i.d)}<small class="subtle">${e(i.u||'')} · Referência ${brl(i.vu)}</small></td><td>${i.q??'—'}</td><td><input type="number" min="0" step="0.01" data-item-cost="${index}" value="${e(q.itemCosts?.[index]?.cost??'')}" aria-label="Custo unitário do item ${e(i.n)}"></td><td id="item-bid-${index}">—</td></tr>`).join('')}</tbody></table></div>`:''}<div id="quote-result" class="quote-result"></div><button class="button primary" data-action="save-quote">Salvar orçamento para a equipe</button><p class="subtle" style="margin-top:10px">O cálculo orienta seu limite comercial. O envio do lance é feito no portal oficial de disputa.</p></div>`;
}
function tasksPane(){return `<div class="pane"><h3>Tarefas e checklist documental</h3>${detailTasks()}<h3>Adicionar tarefa</h3><form id="task-form" class="task-form"><input name="title" required maxlength="240" placeholder="Ex.: solicitar cotação / obter certidão fiscal" aria-label="Título da tarefa"><select name="assigneeId" aria-label="Responsável da tarefa">${ownerOptions(S.member?.id)}</select><input name="dueAt" type="date" aria-label="Prazo da tarefa"><select name="kind" aria-label="Tipo de tarefa"><option value="task">Atividade</option><option value="document">Documento pendente</option></select><button class="button primary">Adicionar tarefa</button></form></div>`;}
function safeLink(url){try{const u=new URL(url);return ['https:','http:'].includes(u.protocol)?u.href:'#';}catch{return '#';}}
function renderDetail(){
  const {opportunity:r,work:w}=S.detail,d=deadline(r);
  const tabs=[['overview','Resumo e equipe'],['tasks','Tarefas'],['docs','Documentos e IA'],['quote','Orçamento']];
  $('#detail-content').innerHTML=`<header class="detail-header"><div><span class="tag blue">${e(r.mc?.[0]||r.cl||'Oportunidade')}</span><h2>${e(r.un||r.org||'Oportunidade')}</h2><small>${e(r.tit||r.id)} · ${e(r.cid||'')} / ${e(r.uf||'')}</small></div><button data-close="detail" class="close-button" aria-label="Fechar oportunidade">×</button></header><div class="detail-body"><div class="detail-main"><div class="tabs">${tabs.map(([key,label])=>`<button data-detail-tab="${key}" class="${S.tab===key?'active':''}">${label}</button>`).join('')}</div>${S.tab==='overview'?overviewPane(r,w):S.tab==='tasks'?tasksPane():S.tab==='docs'?documentsPane(r):quotePane(r,w)}</div><aside class="detail-side"><label>Etapa no Kanban<select id="work-stage">${stageOptions(w.stage||'nova')}</select></label><label>Responsável<select id="work-owner">${ownerOptions(w.owner_id)}</select></label><div><h3>Prazo de propostas</h3><div class="fact"><span class="due ${d.class}">${d.label}</span><small>${fmt(r.fim)}</small></div></div><div><h3>Valor estimado</h3><div class="fact"><b>${brl(r.val)}</b></div></div><div class="source-fact"><h3>Última consulta do cartão</h3><div class="fact">${fmt(r.checkedAt)}<small>${e(r.source||'PNCP')}</small></div></div><button class="button secondary small" data-action="refresh-opportunity">↻ Atualizar prazo e anexos</button><div class="portal-fact"><a class="button secondary small" href="${e(safeLink(r.link))}" target="_blank" rel="noopener">Abrir fonte oficial ↗</a>${r.orig?`<a class="button secondary small" style="margin-top:8px" href="${e(safeLink(r.orig))}" target="_blank" rel="noopener">Portal de disputa ↗</a>`:''}</div></aside></div>`;
  if(S.tab==='quote')updateQuote();
}
function quoteValues(){const q=JSON.parse(S.detail.work.quote||'{}');document.querySelectorAll('[data-quote]').forEach(input=>q[input.dataset.quote]=Number(input.value));if($('#use-item-costs'))q.useItems=$('#use-item-costs').checked;if(S.detail.opportunity.it?.length)q.itemCosts=S.detail.opportunity.it.map((i,index)=>({cost:Number($(`[data-item-cost="${index}"]`)?.value)||0,quantity:Number(i.q)||0}));return q;}
function updateQuote(){const q=quoteValues(),result=calculateQuote(q);$('#quote-result').innerHTML=`<div><small>Custo total com contingência</small><strong>${brl(result.cost)}</strong></div><div><small>Lance mínimo total</small><strong>${result.bid===null?'Rever percentuais':brl(result.bid)}</strong></div><div class="wide">Lance = custo ÷ (1 − imposto − margem). ${result.bid!==null&&S.detail.opportunity.val?(result.bid<=S.detail.opportunity.val?'Dentro do valor estimado do cadastro.':'Acima do valor estimado do cadastro.'):'Confirme a unidade e o período antes de cotar.'}</div>`;(q.itemCosts||[]).forEach((i,index)=>{const cell=$('#item-bid-'+index);if(cell)cell.textContent=brl(minimumBid(i.cost,q.tax??6,q.margin??15));});}
let saveQueue=Promise.resolve();
function saveWork(r,changes={}){const operation=saveQueue.then(()=>persistWork(r,changes));saveQueue=operation.catch(()=>false);return operation;}
async function persistWork(r,changes={}){
  if(!needLogin())return false;const detail=S.detail?.opportunity.id===r.id?S.detail:null,w=detail?.work;
  const payload={stage:w?.stage||r.stage||'nova',ownerId:w?.owner_id||r.ownerId||null,version:w?.version??r.version??0,notes:w?.notes||r.notes||'',quote:w?JSON.parse(w.quote||'{}'):r.quote||{},...changes};
  try{const result=await api('/opportunities/'+encodeURIComponent(r.id),'PATCH',payload);Object.assign(r,{stage:payload.stage,ownerId:payload.ownerId,version:result.version,notes:payload.notes,quote:payload.quote});if(w)Object.assign(w,{stage:payload.stage,owner_id:payload.ownerId,version:result.version,notes:payload.notes,quote:JSON.stringify(payload.quote)});toast('Salvo para a equipe');renderMetrics();return true;}catch(err){toast(err.message,true);if(err.status===409){await load();if(detail)await openOpportunity(r.id,S.tab);}return false;}
}
async function changeStage(id,stage){const r=S.catalog.find(r=>r.id===id);if(!r)return;if(await saveWork(r,{stage}))render();else render();}
async function inviteTeam(){if(!needLogin())return;try{const data=await api('/invites','POST',{});$('#invite-url').value=data.url;$('#invite-dialog').showModal();}catch(err){toast(err.message,true);}}
async function runStudy(estimate){if(!needLogin())return;const result=$('#ai-result'),buttons=[...document.querySelectorAll('[data-action="ask-ai"],[data-action="estimate-ai"]')];buttons.forEach(b=>b.disabled=true);result.hidden=false;result.textContent='Lendo o material e preparando '+(estimate?'a estimativa de custo':'a resposta')+'…';const id=S.detail.opportunity.id;
  try{const data=await api('/opportunities/'+encodeURIComponent(id)+'/study','POST',{mode:estimate?'estimate':'ask',question:$('#study-question').value,assumptions:$('#study-assumptions').value,documentIndex:Number($('#study-doc').value)});if(S.detail?.opportunity.id!==id)return;result.textContent=data.answer+(data.truncated?'\n\nDocumento longo: a análise recebeu um trecho parcial.':'');toast('Estudo salvo para a equipe');}catch(err){result.textContent=err.message;toast(err.message,true);}finally{buttons.forEach(b=>b.disabled=false);}}
document.addEventListener('click',async event=>{
  const target=event.target,close=target.closest('[data-close]');if(close){$('#'+close.dataset.close).close();return;}
  const view=target.closest('[data-view]');if(view){S.view=view.dataset.view;if(['archive','atas'].includes(S.view)){if(!needLogin()){S.view='board';return;}try{S.archive=(await api('/archive?kind='+(S.view==='atas'?'ata':'opportunity'))).catalog;}catch(err){toast(err.message,true);}}render();return;}
  const tab=target.closest('[data-detail-tab]');if(tab){S.tab=tab.dataset.detailTab;renderDetail();return;}
  const more=target.closest('[data-more]');if(more){S.columnLimit[more.dataset.more]=(S.columnLimit[more.dataset.more]||30)+30;renderBoard();return;}
  if(target.closest('#invite-team')||target.closest('[data-action="invite"]')){await inviteTeam();return;}
  if(target.closest('#copy-invite')){try{await navigator.clipboard.writeText($('#invite-url').value);toast('Convite copiado');}catch{$('#invite-url').select();toast('Selecione e copie o link');}return;}
  if(target.closest('#refresh-workspace')){await load();return;}
  if(target.closest('#export-snapshot')){try{const data=await api(S.member?'/workspace':'/catalog'),blob=new Blob([JSON.stringify({exportedAt:new Date().toISOString(),scope:S.member?'acervo e quadro da equipe':'acervo público',notice:'Exportação do estado atual; checkedAt é a data da consulta oficial de cada registro.',...data},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='licitacoes-snapshot-'+new Date().toISOString().replace(/[:.]/g,'-')+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Snapshot exportado');}catch(err){toast(err.message,true);}return;}
  if(target.closest('#sync-pncp')){if(!needLogin())return;try{const result=await api('/sync','POST',{});toast(result.message);await load();}catch(err){toast(err.message,true);}return;}
  if(target.closest('#clear-filters')){S.filter={q:'',uf:'',owner:'',service:'',deadline:''};$('#search').value='';$('#filter-deadline').value='';populateFilters();render();return;}
  const action=target.closest('[data-action]');if(action){
    const kind=action.dataset.action;
    if(kind==='login'){openAuth();return;}
    if(kind==='logout'){await api('/logout','POST',{});S.member=null;S.detail=null;$('#detail').close();await load();return;}
    if(kind==='ask-ai'||kind==='estimate-ai'){await runStudy(kind==='estimate-ai');return;}
    if(kind==='save-work'){await saveWork(S.detail.opportunity,{notes:$('#work-notes').value});return;}
    if(kind==='save-quote'){await saveWork(S.detail.opportunity,{quote:quoteValues()});return;}
    if(kind==='refresh-opportunity'){if(!needLogin())return;action.disabled=true;action.textContent='Consultando PNCP…';const id=S.detail.opportunity.id;try{const data=await api('/opportunities/'+encodeURIComponent(id)+'/refresh','POST',{});if(S.detail?.opportunity.id===id){S.detail.opportunity=data.opportunity;renderDetail();}toast('Prazos, documentos e itens atualizados');await load(true);}catch(err){toast(err.message,true);action.disabled=false;action.textContent='↻ Atualizar prazo e anexos';}return;}
  }
  const open=target.closest('[data-open]');if(open&&!target.closest('select,input,a'))await openOpportunity(open.dataset.open,'overview');
});
document.addEventListener('keydown',event=>{if(event.key==='Enter'&&event.target.matches('.card,tr[data-open]'))openOpportunity(event.target.dataset.open,'overview');});
document.addEventListener('input',event=>{const t=event.target;if(t.id==='search'){S.filter.q=t.value;render();}if(t.dataset.quote||t.dataset.itemCost!=null)updateQuote();});
document.addEventListener('change',async event=>{const t=event.target,map={'filter-uf':'uf','filter-service':'service','filter-owner':'owner','filter-deadline':'deadline'};
  if(map[t.id]){S.filter[map[t.id]]=t.value;render();return;}
  if(t.dataset.cardStage){await changeStage(t.dataset.cardStage,t.value);return;}
  if(t.id==='work-stage'||t.id==='work-owner'){await saveWork(S.detail.opportunity,{stage:$('#work-stage').value,ownerId:$('#work-owner').value||null});await load(true);return;}
  if(t.id==='use-item-costs')updateQuote();
  if(t.dataset.taskToggle){if(!needLogin()){t.checked=!t.checked;return;}try{await api('/tasks/'+t.dataset.taskToggle,'PATCH',{done:t.checked});await load(true);if(S.detail&&$('#detail').open)await openOpportunity(S.detail.opportunity.id,S.tab);else render();}catch(err){t.checked=!t.checked;toast(err.message,true);}}
});
document.addEventListener('submit',async event=>{const form=event.target;if(!['auth-form','task-form','comment-form'].includes(form.id))return;event.preventDefault();const button=form.querySelector('button'),body=Object.fromEntries(new FormData(form));
  if(form.id!=='auth-form'&&!needLogin())return;button.disabled=true;
  try{
    if(form.id==='auth-form'){const data=await api(invite?'/register':'/login','POST',{...body,invite});S.member=data.member;invite=null;history.replaceState(null,'',location.pathname);$('#auth').close();await load();if(S.detail)await openOpportunity(S.detail.opportunity.id,S.tab);toast('Bem-vindo ao espaço da equipe');}
    else{const id=S.detail.opportunity.id;await api('/opportunities/'+encodeURIComponent(id)+(form.id==='task-form'?'/tasks':'/comments'),'POST',body);await load(true);await openOpportunity(id,S.tab);toast(form.id==='task-form'?'Tarefa adicionada':'Comentário publicado');}
  }catch(err){if(form.id==='auth-form')$('#auth-error').textContent=err.message;else toast(err.message,true);}finally{button.disabled=false;}
});
document.addEventListener('dragstart',event=>{const card=event.target.closest('.card');if(!card||!S.member)return;dragId=card.dataset.open;event.dataTransfer.setData('text/plain',dragId);event.dataTransfer.effectAllowed='move';card.classList.add('dragging');});
document.addEventListener('dragover',event=>{const column=event.target.closest('[data-drop-stage]');if(column&&dragId){event.preventDefault();column.classList.add('drop-target');}});
document.addEventListener('dragleave',event=>{const column=event.target.closest('[data-drop-stage]');if(column&&!column.contains(event.relatedTarget))column.classList.remove('drop-target');});
document.addEventListener('drop',async event=>{const column=event.target.closest('[data-drop-stage]');if(column&&dragId){event.preventDefault();const id=dragId;dragId=null;await changeStage(id,column.dataset.dropStage);}});
document.addEventListener('dragend',()=>{dragId=null;document.querySelectorAll('.dragging,.drop-target').forEach(el=>el.classList.remove('dragging','drop-target'));});
$('#detail').addEventListener('close',()=>{S.detail=null;render();});
window.addEventListener('hashchange',()=>{invite=new URLSearchParams(location.hash.slice(1)).get('invite');if(invite)openAuth();});
async function start(){try{S.member=(await api('/me')).member;await load();if(invite)openAuth();}catch(err){$('#content').innerHTML='<div class="empty">Não foi possível carregar o quadro. Use o botão de sincronizar para tentar novamente.</div>';toast(err.message,true);}}
setInterval(async()=>{if(document.hidden||polling)return;polling=true;try{await load(true);}finally{polling=false;}},20000);
start();
