import {escape as e,dateTime,isLive} from './core.js';
import {inlineTabs,documentLinks} from './inline-opportunity.js';
import {goalLabel,reasonLabel} from './goals.js';
const money=value=>value==null?'Valor não informado':Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=value=>dateTime(value)?.toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})||'Prazo não informado';
const safeURL=value=>{try{const u=new URL(value);return ['https:','http:'].includes(u.protocol)?u.href:'#';}catch{return '#';}};
export function triagePane(rows,goal,member,lastDecision,tab='overview',pane='',floors='',brief=''){
  const candidates=rows.filter(r=>r.scope?.level==='in'&&(!r.stage||r.stage==='nova')&&isLive(r)),r=candidates[0];
  if(!r)return (lastDecision?'<div class="triage-undo"><span>'+e(lastDecision.label)+'</span><button class="text-button" data-undo-decision>Desfazer última decisão</button></div>':'')+'<div class="triage-empty"><h2>Triagem em dia</h2><p>Nenhuma nova oportunidade AD PRO com estes filtros.</p><button class="button primary" data-view="board">Ver o Kanban</button><button class="button secondary" id="clear-triage-filters">Limpar filtros</button></div>';
  return '<section class="triage-wrap" aria-label="Triagem rápida"><div class="triage-progress"><b>'+candidates.length+' para avaliar</b><span>'+(member?'Decisões compartilhadas com a equipe':'Entre para salvar suas decisões')+'</span></div>'+(lastDecision?'<div class="triage-undo"><span>'+e(lastDecision.label)+'</span><button class="text-button" data-undo-decision>Desfazer última decisão</button></div>':'')+'<article class="swipe-card onepage-card" data-swipe-card="'+e(r.id)+'" data-version="'+e(r.version||0)+'" tabindex="0" aria-label="Oportunidade para avaliar"><div class="card-head"><span class="tag blue onepage-category">'+e(goalLabel(goal))+'</span><b>'+e(r.cid||'Cidade não informada')+' · '+e(r.uf||'BR')+'</b></div><h2>'+e(r.obj)+'</h2><div class="tender-identity"><div><small>Licitação / modalidade</small><b>'+e(r.numero?r.modalidade+' '+r.numero+'/'+r.ano:r.tit||'Número não informado')+'</b></div><div><small>Órgão / unidade</small><b>'+e(r.org||r.un)+'</b><small>'+e(r.un&&r.un!==r.org?r.un:'')+'</small></div><div><small>Cidade / UF</small><b>'+e(r.cid||'Não informada')+' / '+e(r.uf||'—')+'</b></div><div><small>Valor estimado / propostas</small><b>'+money(r.val)+'</b><small>'+date(r.fim)+'</small></div><div><small>Controle PNCP</small><b>'+e(r.id)+'</b></div><div><small>Processo</small><b>'+e(r.processo||'Não informado no cadastro')+'</b></div></div><div class="onepage-source-links">'+(r.link?'<a class="button secondary" href="'+e(safeURL(r.link))+'" target="_blank" rel="noopener">Consultar PNCP ↗</a>':'')+(r.orig?'<a class="button secondary" href="'+e(safeURL(r.orig))+'" target="_blank" rel="noopener">Portal da licitação ↗</a>':'')+'</div>'+floors+brief+documentLinks(r,member)+'<div class="onepage-tools"><div class="tabs inline-tabs" role="tablist" aria-label="Consulta adicional nesta página">'+inlineTabs.map(([key,label])=>'<button role="tab" aria-selected="'+(tab===key)+'" data-inline-tab="'+key+'" class="'+(tab===key?'active':'')+'">'+e(key==='overview'?'Ficha completa':key==='products'?'Atualizar produtos':label)+'</button>').join('')+'</div>'+(tab==='overview'?'':pane)+'</div><button class="text-button triage-details" data-open="'+e(r.id)+'">Mais opções da equipe ↗</button></article><div class="swipe-actions"><button class="button decline-button" data-triage-decline="'+e(r.id)+'">← Recusar</button><button class="button accept-button" data-triage-accept="'+e(r.id)+'">Aceitar e ir ao Kanban →</button></div><p class="triage-help">Aceitar salva mínimos e produtos selecionados. Recusar exige motivo. O envio efetivo é feito pela equipe no portal oficial.</p></section>';
}
export function declinedPane(rows){const declined=rows.filter(r=>r.stage==='declinada');return '<div class="declined-grid">'+declined.map(r=>'<article class="declined-card"><span class="tag gray">Recusada</span><h3>'+e(r.obj)+'</h3><p>'+e(r.org)+' · '+e(r.uf)+'</p><p><b>Objetivo:</b> '+e(goalLabel(r.goal))+'</p><p><b>Motivo:</b> '+e(reasonLabel(r.declineReason))+'</p><div class="ai-actions"><button class="button secondary" data-open="'+e(r.id)+'">Ver detalhes</button><button class="button primary" data-reevaluate="'+e(r.id)+'">Voltar para triagem</button></div></article>').join('')+(declined.length?'':'<div class="empty">Nenhuma oportunidade recusada com estes filtros.</div>')+'</div>';}
