import {escape as e,dateTime,isLive} from './core.js';
import {inlineTabs} from './inline-opportunity.js';
import {goals,goalLabel,reasonLabel} from './goals.js';
const money=value=>value==null?'Valor não informado':Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const date=value=>dateTime(value)?.toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo',day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})||'Prazo não informado';
export function triagePane(rows,goal,member,lastDecision,tab='overview',pane='',floors='',brief=''){
  const candidates=rows.filter(r=>r.scope?.level==='in'&&(!r.stage||r.stage==='nova')&&isLive(r)),r=candidates[0];
  if(!r)return (lastDecision?'<div class="triage-undo"><span>'+e(lastDecision.label)+'</span><button class="text-button" data-undo-decision>Desfazer última decisão</button></div>':'')+'<div class="triage-empty"><h2>Triagem em dia</h2><p>Nenhuma nova oportunidade AD PRO com estes filtros.</p><button class="button primary" data-view="board">Ver o Kanban</button><button class="button secondary" id="clear-triage-filters">Limpar filtros</button></div>';
  return `<section class="triage-wrap" aria-label="Triagem rápida"><div class="triage-progress"><b>${candidates.length} para avaliar</b><span>${member?'Decisões compartilhadas com a equipe':'Entre para salvar suas decisões'}</span></div>${lastDecision?`<div class="triage-undo"><span>${e(lastDecision.label)}</span><button class="text-button" data-undo-decision>Desfazer última decisão</button></div>`:''}<article class="swipe-card" data-swipe-card="${e(r.id)}" data-version="${e(r.version||0)}" tabindex="0" aria-label="Oportunidade para avaliar"><div class="card-head"><span class="tag ${r.mc?.length?'blue':''}">${e(r.mc?.[0]||r.sv?.[0]||'Software')}</span><b>${e(r.uf)}</b></div><h2>${e(r.obj)}</h2><div class="triage-card-grid"><div class="triage-analysis"><div class="tabs inline-tabs" role="tablist" aria-label="Oportunidade na mesma tela">${inlineTabs.map(([key,label])=>`<button role="tab" aria-selected="${tab===key}" data-inline-tab="${key}" class="${tab===key?'active':''}">${label}</button>`).join('')}</div>${tab==='overview'?'':pane}<div ${tab==='overview'?'':'hidden'}><p class="triage-org">${e(r.un||r.org)} · ${e(r.cid)}</p><div class="triage-facts"><div><small>Valor estimado</small><b>${money(r.val)}</b></div><div><small>Prazo de propostas</small><b>${date(r.fim)}</b></div></div><div class="goal-choice"><h3>Qual é o objetivo comercial?</h3><label class="mobile-goal-field">Objetivo comercial<select data-triage-goal>${goals.map(([id,label])=>`<option value="${id}" ${goal===id?'selected':''}>${e(label)}</option>`).join('')}</select></label><div class="goal-chips">${goals.map(([id,label])=>`<button type="button" data-goal-choice="${id}" aria-pressed="${goal===id}" class="goal-chip ${goal===id?'active':''}">${label}</button>`).join('')}</div></div>${brief}</div></div>${floors}</div><button class="text-button triage-details" data-open="${e(r.id)}">Mais opções da equipe ↗</button></article><div class="swipe-actions"><button class="button decline-button" data-triage-decline="${e(r.id)}">← Recusar</button><button class="button accept-button" data-triage-accept="${e(r.id)}">Aceitar →</button></div><p class="triage-help">Deslize o cartão ou use os botões. Aceitar leva para Compatíveis; recusar exige um motivo. A triagem não substitui conferir o edital.</p></section>`;
}
export function declinedPane(rows){const declined=rows.filter(r=>r.stage==='declinada');return '<div class="declined-grid">'+declined.map(r=>`<article class="declined-card"><span class="tag gray">Recusada</span><h3>${e(r.obj)}</h3><p>${e(r.org)} · ${e(r.uf)}</p><p><b>Objetivo:</b> ${e(goalLabel(r.goal))}</p><p><b>Motivo:</b> ${e(reasonLabel(r.declineReason))}</p><div class="ai-actions"><button class="button secondary" data-open="${e(r.id)}">Ver detalhes</button><button class="button primary" data-reevaluate="${e(r.id)}">Voltar para triagem</button></div></article>`).join('')+(declined.length?'':'<div class="empty">Nenhuma oportunidade recusada com estes filtros.</div>')+'</div>';}
